const Assert = require('assert')

//#region 
let input = 'UjVvhHOKkRrOooNpxXPnJjJnGgNyYmMtThHusqvVQXUCcuHhxJjcJjCsSHhfFzZQEXxeqNEedVvDpPco' +
  'OCxXfFrRIPrROopOOoEeGgEeoYAayhHZzhHaAWwiJjnmMXxNmMnWlLKkbgGBwWOoqQwLVvIilOCcbBoB' +
  'bJjEmMuUefFkKbBkMmJjjnrRBbNFfoOJdDeEgGOOoTsSQqHhSstoJtuUTjscCZzxXHtThxfFXSxXuUHh' +
  'KOofFNGghBbHkKHpuUPEeYsSvVoOyoOlLhwJjfFWwWvvVbNNnnnNNsSvVnFfWwxuUKKkOoEiIekNniIq' +
  'QXULlrRuZBbzWMFfmtQqeEkpbfcCFBbmOoMBPKTHNzZnhsSwRrUEoOFfeuRzQqZrcCGupgGPESsWEeeE' +
  'zZuUwekKpPbBIiwWXxPpdDsSelLEraAKkIOoGgiRqbBQzZXxlxXLQyYvVKkiRrXxPpQqImMUuhcCYHhM' +
  'muUybPpBdWwSfJjFBCcbsKZzkBbMNnmgfFGnQqNfFpPoOKOokiqAamMpPXXxlLxTYybBtcCbBQnwWMmL' +
  'kKlNIEeHhnuUNScCsfFQxXqCRrceEFfqQmkfFKMJjqQjJqQTtnfhHLlFeEWwNKkjJWwhuUiIdDSSQqnN' +
  'syYCctBrROobTscvruUzNnoOGgZkKmLuUlMmFfMiIRpPVxXBbRroOyYtTuUVWsSwDdDdSsSsxXvgqilL' +
  'uUDdInVvNQEeGkKRrzZuBYBbKmBbyYMishHSVpPvzZIsHhKkSCcxXFDdfIyqQfFYiSsXxnNlLjJGgMbJ' +
  'jtTCcBjbBjJJWwWwnuUNmMyZzPpGgVvgGQetfFTfFEqYDdmqQMPpmsSTkKHhxXzZkiIZzLlKuURqQXxA' +
  'CckKarHhbzZzCcZBCcxXiwWfFClSsZzITEetEeIiiLhfFHKkKkgGyYcaArRHdDzZjJRrhbWpPggGGwBG' +
  'nCcJjNgIxpPXeEOoXSfFsxWcCNCcnwbBrRIizZTMmtIioyYOlXxFfUuLPpoeEnNYUuuUyayJCcCcWwjW' +
  'wnNYMmQqqQAQxXqQqMmCcObBDdMedVvDJjOoEEuUojJOeMVEevByYbmzZfAaLlFwWFfzZbBRrmYyBuaA' +
  'UbBbgsCcSaAKZzBbkcCFfVvGxXRPpuIuUibBsSLlYJaAQdDpWwPqsSaAMmVCchHaAvOZSszotTIiHfnN' +
  'utLlTIiDdVvRrpUuSseEuUPUyYPmMpfXxbBhHFXxrOoXxRGppPpPPDdglCVPpSsvfFcdDFPpmMEegOjJ' +
  'oaAmyYModDaAOoAUuaOfrRTtFWwoyYlMmbBLYylTuXxEeUtFfLJjEKkevOSsHhfFjJoeEFfDdVKmhEyY' +
  'mMGgTtdDIvVipPaAeIfFiUuGgUVvQmMqffcCJjqQlLERMmreitfFTUuTJKkFEeQqmAGgFfRrAaaMfcIi' +
  'CYNgGfFYyJjwIiWniIZzyFeERqQoOrQbBqgGfjNnZztnYyNBLpPlcCuUgGZzwWSssSVvMLzoOBbZlmaR' +
  'rPpTtAZzLNnlFfLUrRWwxXBbdBbZzbBYyzZDKWwgGkTtCcnTzWsEHcChdzZDmiIZzMeSaAtTfFaDdoOH' +
  'hAwKWwqQUxXsQvVqobBoOORJjrMrIiRrRlfFLmqQSsJjxXEeSujKtXXFfxxGgTkbbBBeMmdcCeEIivAi' +
  'IalLOeEgkKUuGoOrvVRxXXxpPRrojBcCbJmMEeXxdDXxglVvAaqQLUuGwYyWKwlLWCzZMoWwOZCczOop' +
  'CcPVSqQsvGbFfySsBbnNlLYBbBgqQjhBbHJtbOMkdDKmeEotTyYgGBrRsUbOoBRruSsfFJjzZiItTkKW' +
  'wSbBjmMgGJMmjSXxsFZzQuUqfJLlgGRreLwWlEGgoupnPpNkKPldDSBWwAawWrRbsyYLmMQqOPeEMMmm' +
  'XxoOPgRrZzlLOoJTtjGpwWpXxIiFCcjcCVvJfsbBsSSOoUEllRrLLkKKhHhFRrfHQqkZzyKkYBnNbuez' +
  'CcSsKLlkZEuUFfPpqQCcUYoOyvVpPshLlmMoOoOiIskIYluULyiiIKSOqQocCJjicCICLyYeRrJjAaEJ' +
  'jbBlMDdmcpyYPoySsYOuUTtCcJjSscCJxeEiIsSNnmcCMqQLlGGgIigmYyMYyhqpPQHhBJjbeNuUiInE' +
  'jvVJtTyYSDdeELvVKkCtUuTcvVxXZzlsRPOoyYpHhcCVvcCGEegYrRhHyyUuYXgGxRquUpPCcaAYyQrm' +
  'MUAaoOIipPhHuaAGwWEeiGgIkKdnNDgyYNbSxXsBnweEIlLmlLjJjJMnryOoYRzZeYyfFYyENAaiKkvj' +
  'ZzJpPVByYzvDdYGgJjeiIEctmMBbTgGLEelNnCykjJRfFraAWiIwetTEQqBbrRzZujTtJYoeEJjOeEWL' +
  'lLlbBEVviDdBbIeJjwyCDdceZztTfHzZhFEeGgRTtrczZCcCUUuuEChHckKoOUSuUbFfOoBJqFwWpPfQ' +
  'JjdDjgGyiIYVvwpfFLlPIiMmWJLltTjrRvVLlEesNnfCwWDdcFInNIKqQkOoIgGOoiYETtGTtcCneENu' +
  'iIOoPpdWwDOotFoOtTfTsuUCuRrUCsJjZzfFlcUuAEeaCQqYyWCcwaARpPSsNnrLSRbxXBRrxXRrTtHh' +
  'rvVoOQFfAaeEufFAeUuEvWmtTMCcmEeFfpPMRrVWwvaAcOeEMfFcCtTTtiDJjfNXTtIixnHzZbsSAaBD' +
  'dYyAaodSRUeEvVuZzrVvKkcqfYZzZopPORadDApQsSKkkKqPrzWwKYWwykWAatTXASsMpPmYygxTAanN' +
  'dDtXGvVLxFfQDdHhqBbXgGcCyYwWUuCRrfVvFYyVvPpNnPAapTtaAUukKuUvKIiYyyYxAaiIXGiIMmgk' +
  'VldDNnJjSlNSstTrRnzsSZLwAaLlwWvJOOMmooJjCcTiBBbARrabIaAUlLuuUzZcgGBbCjDdJjRyXxZz' +
  'YSsdDpPrJZfPpIiLlFYyUubgQqGBicEXxeRrZvVzCItTHhzgGZzFfZJzZmMjRrwWZmvVMRrnhTVxXTtv' +
  'tzZBbHOqQosPpSlLOsSHhoxVvXWwwWmMNTtiIYyplMmLpDEedPPmMxXsSrRRrRrZzIiUuyYmMIonIiNO' +
  'iDdghHJhTtJYyjvVrRGgHKkjlnLQqsSOoRyYrKGlLAgGWwaQRryNnYEeYyQqjoOiIkKsSBbosSrPpRTt' +
  'rjJRHhSssdDxXFfYyzdDqQmfFyYMkKOdoOAaDiIlLxXuhHUdaADOowlLWkKetybBYiIXlLYDdiISsOom' +
  'MTtITtvWdDwNmMnViKkeGgEeEYyqQiILlcPpCQZwWedDEhHzqiwbBWiIIakdDHhsuULGglvVgGdfFDxT' +
  'tuUHhXeHuUhGwWgEbbBxXZzRrjJBdSskmMjhRtTraArRovkKVmAIiaGpDGeEesSEgPKkSAvpPVGgjJal' +
  'LkKCcQqqVvrRYyQsANjJVveEIuSskKNnaYsSyDdRYyiIrjzZzZJpCcKkPmpPpPdDqQYLlyBdnNtTAaZj' +
  'KkJsSOgGodDxXeEIiFsSfiIjJBwoOWxXwWxXBbLsFfhHenDdsbBSNfFEgiIGUsTQqtAaSZzuwZzWTtxX' +
  'qsSJGgoOOouFfEeRrUjZzQJjSjBbJyFPptThyKFfrRkGBbgLlzxhHjzZXxHhRrOoXxRrAvVKBbkaiIzn' +
  'NYlLIiXxSsyQqfFjmMFWyYpPpOonNpPPEeJjrxXgGZpPzRwqpPQeoOQWwqGNnqwWvVlLRrRMmeEWAkKa' +
  'wUunHhOJjAGFfgaoDnNWwIaAijmMLlJHhQqWwcCvVpPdlXxLWwKQqLlskiZzcCIAaKHhSgXjJxfFSsqN' +
  'nQGgURrSgxXGBYybKeEjxXpPJVKkOFfstTHhyYrRAYyaKIiprRSsTHhtjJAKksSsSCpPPpcaAcFFViic' +
  'CIILhSsHltLljJAaTEElLUuwWIbYyBaAREwWQqSsNnyYyYFfeeENyyYFhLloOLlIiHhdDlLHCEwWFfum' +
  'MUsSwKkWzZqQlLoeXBbxEIjJQqixIlLFvEXxKyYkeVvjWwJVMmvVrjJfSuUsaAFOoQqJjRmMfKkHhzZh' +
  'RrYyvVHfMQhHpPuUqMsSmBGgkKaxNnqQiIXAjJZzbkwWzZsdpMmCMmcCcPuUyYBKkbqIibBnFtTfIXxg' +
  'GiNNnQSGgGgWbBiIwiFLlffEeHhfFvnNVrsZzuUSRoObqZzQoqQZzuVvUOhHwrRWLlFRrGIigGUughHM' +
  'mfZYuUyzIbBirozZOjdDRwWDdyuUAnvdDVBbNEeUfFdIiDrRExXtDkEeKzZdkowcCWSbBsOKhHwJjWmT' +
  'tZzMpPKkrGgRwWeqQepPQqEaAXxYXxyxOJjoDicCdDmMCCalLsSACHKkhcSsyYRrjMFfmMmJKkPpUuTK' +
  'kSIiUuDYydNnrRpsSYyTtiIvBFYyAlLYyYyalLpPXaAoRrxQqXOdqQCcDxDdZsfzZEoZzOHsSheFByYb' +
  'RrnNVvfaAlzZLFJwWjqQoOFfiTtymNlgPpGeENnaArRKGgsSklLUuSspEeLlxdDVyYVvdDRrNnoOHhpP' +
  'DfIiFdmMAatTMvVjJfFAaZzbQqdLlKkhHvQqVAaDYyoOrjJFfWwRMmmMeMmJjXcCXxIEeixxcuQqUKkP' +
  'pZzCvVhHyYvVvVcCVvMaYyAwdDfooOOaATNntxeNneELlKZzkkmfHnNaAVNnvFfBZzbhNhCcVvKkQqdD' +
  'LaQqtTAdDTtBoObDdUuBXxDUudbkKmwWGwWgMnNaAzZrHdDdDhdSOoslLZzhYypHhhHPrhQqxuUjJXyY' +
  'xXWxXcwWeLlPpfFEMmitTsSIoOiIiImMvVCEeuUcCtWtYyCcTwMeEmumMoOULlRwWDIUuieEhHoOseES' +
  'dOoOSLlnNSslLpiIPXxPTUiIjhHDdTFtDdTfLiIiIiIvWnNJXxZzjmFfWwhxXqQqQwWiIHpPTOjkKOLP' +
  'BbpeElfFfyYFxXPcCyYMUumpKaAaAegGUubBEdBbDikKIMdDVvqQmNFBbfVvuUGwWRXgGMBKkbdDXxmx' +
  'cCdDmfFMUurPpsScCDEeBbxXeEyYyYtTbBLJjFfldgnfpPFLlhwNnuUWxXpIiPgGXxvVHXxmMNDCcWwd' +
  'PUuxXgGtuUuvVUMsMmSmhHhHTWYaAywIuUHhnNXoSsLrRlWwfOoFSWwXpPxfvVlLFsqRlLRpPnNnNMmr' +
  'eEAadeEnNAaTtlRrLbRraATtrcCRQvVLlsqQLGjNnKAakzfCNZzuUnZVvJWwjrRCVKkvrRbrRBcoOTtp' +
  'PTtzZzBGgeEbIikFbBNoEeOnuUfEPoOpeKZOEeoEtTeZSjKklpPFfLkKnNhHRrQXwWbyYBZzxOoCXnck' +
  'KCNTCctxIiEecaAmMmhHxXMpHQqjJzpTlREertTLuUfFOwWZHhztsAaetyYjJJjrznNnuWwUxXuUBxXA' +
  'aIOtToHhOoirRtTbNZRtTdDTSKAaBbRrMCTtVvXxSoOZzLcNAanCsaSsASlDdVvvVhznHyYhNqQFfuUZ' +
  'OoHGbBgSkKsvVGgOcCsSoeDdQqymuUGgHhMYdhHkwWdFwNqQnKkWCcOKYrRZnLXawWnNFJlLjHkKLltT' +
  'pqQPBnNamMgVvGyYyOoYnwvVWNCcvVyMDdjJOoQJjqcCTtTBEehHCpPcnNlLvpPOosSslFqdBbnFaAfQ' +
  'qDdVvNUKkbBSsugGnNJjpGIxEFfesSjeMmEJXMVvGVvgiIXhHxmXxUsSxTtXpPtTFTNntKkqvVPudDUG' +
  'MmFfsaAjJSRroTtOLlBbzHhxXZCcOxQkAasSBeENnbGTtgLlKkHzZdDbBhYvOoDEuuHhUMmLJjlqkKDd' +
  'QZzMUumUwWNSYyseThHtEnuMmUVvucCUzZjbBJPZzZzNnIbhUuJjHeEBpXxVvBlVvtuUpPhHTgGMmJfF' +
  'iIIiTtEerRSsjMmyYdqcCQpOnNEeoPmMivVmXgaDdACcaRrLTtTwRrjJIuUuuUGaAgUjdDbBZzJqQbBT' +
  'ExkKeEuUWbUuBhHCcutTUQqwWEkKeAaZWLlMmwzwmrMzZaAbKkBMlonNODOoFfCyCyYMEelPpJjYknNK' +
  'PDdNnetTwIPpJNnjbZMmzhHkKkKSsusSTVvwWmMtSsaEeAzUPpuOoEMXxKkmaAupWwJsTtWwbVvBUgye' +
  'tTHhhHIiDMQrRqSmRcCUurzZBddDDblLCcPxVeyeEYWwkKiQqgoOFSwiXDdDLeEzYysSZjJlDITtTtuc' +
  'CRGgnYkDsSKkdKdTtcCDcPpPpCzZWbuhuUHnNUAagMASsamKqLlYyfFOuXxtTwWwEevVWSkAaKsvVggV' +
  'PpvzPpPaAmMsShHpGgXxQqJWwjZuPYyxndDNGgBFfWfJjnNdDrDbDdBOoHAaYyYcCksmgGmcyYCcjJlm' +
  'FfCxXcJTtjUuMCAaXxtxXiIrMmRTCcTtcIIaAqQiIioObBlxXLqQinNJsShHhkKvVHjEHhYhHdDjJBZq' +
  'QzInNNnBOobEerRQqibMmcCBIqOKkgEekKRrGFfEevtTNnWEewHjWTtuUvVwbBDdJuUNYygYJBbzZpPa' +
  'bBTfsSFOTtYLNnXxleEGRcCMLlzLlZbBZztTmwWnNIizfcWwdDpPDpPAazdNDcCdnLVvKklGIfFigcCj' +
  'xXJEFUVQqQmMqGgEevXxufnDdkKsSOfHJjOYyoVvYyaAaAIvViwuwWQvfFVrRrRqWRrapPAvVZHZbXxj' +
  'JtTBpPZkNtYyTnKmMhHuUkKoQqOVvjJvVgCxXdDaAUuQHAaYhHybRrVvKZwlLWbdDzQtTQIiqIiqEeiI' +
  'lLnNEutVvyYhHdqQAaDDdAstaATaAsXxTtKkPTFMmJjrRhMlLmfFWwHfTFaxXAUHhuCcUbBuGvVgsOoY' +
  'ySvVgKkGmnNMlLdvVzNkKfzZFCxGghNnHRxWwMmXcIHhiwWWwSAcuUBsIivVWlDuUlLdZuUIiFmMtidD' +
  'yYIDdSsctTiGgItTCcSLBbrNVvnwukKwWMQqAgdLuUltTfDdkKthHTBbtTFGuUwWGggHUuLfFCLluUcl' +
  'JLLlljmBbFfMKgIJjcRrKuUxXkWwgjJGtTDyYdaAfFpPxRyoOjxXJQqYTUuqQtaJSsjyZzgWEgGLlHhw' +
  'WkPGgpKPgGXRFfrfFxCcXFvVfxGgabrRBAGoQnNqQGgqtBbiUuPpDDJNnYSsyxXRrESsJYQqyPpmSLlv' +
  'VsFfqzZOoQdDMIyYiRrQTtWwdDtgGgvVQqVvGnNKRrIiHhHibJjsSuwWUrDdRlLbGrRjJgPprqQRvUux' +
  'XcCuhGdkoOKDVvSsaEeobBOCcnRrHhMNCbBcOtOSsoDdTEbBSswWeNNnXbBIkUunNUukKWwjJKbeEXxA' +
  'aGgwmMWwZsSzOoujHGnNnuUxDMqQMxvVvdDQqoOtTSsYyVXAgwzZejNqQdDAPpaXYUuYyjJLlLxpmMPX' +
  'AaXxCXxWEKkewiIAwWRUurwWkKnNaEeeLlELLLlllpltToObNEejJNApPoOauWwEbSsBZzAawSsVnNrR' +
  'rfFyQsSqhmMKkHRsSFfcEeCTtentbRrBuUVXxPoOknbBtMiIPoOoOlLlbfFgdeEDpPGCcnNYgGyEeYyV' +
  'vvDeVPsSpvEsSuCcnBbDdNKknUuZgGzNuUjJgGmZzTDdGNnwWVvxDwODdolLlLiIWdUunbeEBMGFfTgG' +
  'tGiIpgGwWsSNnuUyYTtPOiIodDaLuUlnNGscCSgLKkHUuPqnNQsVvRrSplZzVsSvLEegxFfZzTtcIidD' +
  'CFCcRiIBxOJSsjAawjJRrpgGKArUkKDDddqjvVPpDdinNOosZzVvSNGgGfFvdDVAaFfmnNmMMfQqFqQz' +
  'pYwdnNDWiGxorCZkKpVvPaYyAkKdZtoFGgLlkgqQkKGJvVlLjBbKmcfFncCqQEevDdPdDdoODpINluUL' +
  'hHnSfbBFiIsmMTtZdDHhziKZzkzZpWoOLlwJjzZVvJjSsINnDdjJjzgGhmZzPpVcrRXxtTOoCMmvGrNB' +
  'bnAajJOweEWSAPVvnNthHIqQiTtypPYThGAfrRFfFWqaAUwzZXyEevyYVqQEeFfnlLeSiIwaAWsEOyYz' +
  'ZoMmoAVmMcXTPpxQqXHURfFOYyaqtTQAfFSsdDSsRSNnuUNHhyZzYOJjhHGgXxyXxYgWNjWOmMAaEeAx' +
  'XTtafkKpPIigGbrRuUolLlmpPiIWeakKgGLlgoFfOnNXxBbxXGYWwjJyQcCTMAamcMiYyIGgTtkADdJa' +
  'AfFjwWaZzwNnsGoBoGOdDJfFkKjuUfFlLjvVjpCcBbLwWOoUulrRzqoOFfQxXtTbiIbBBeLOolESsZIi' +
  'qQViIvmMPpPAiITtvOoGwWzZSPpsepUufMHpPmMLlyYkURrDdZzuKhKSsdCdDGgXxbtwWTbBkqQgGMIk' +
  'WwKivVdGgGnNoOKkMrRpPmSsDdHMxXiIdDxJjXwWmmSegfUHcaACuUvVepLcClKkwvVTtAaAaOtTxXAa' +
  'NnBcRKnHilLIRcCgGCcriEelzZNnCzZeFembIcQqCqcCfaAFQxtNnTYygGNmMnnNDLlrxZNnzSqQJvjU' +
  'BIlSsoOiQjJqDddBHiIhEcNnQqTtMmCOozGCcgsSZeHWwhwWTSsuXHCclKMmuUaRroOoriIawkKHhaeE' +
  'AIGgKqyYRrjJzZvCxXpSsPcqQyHhYoeEBbUFfQquSsuwPpWfFURrCckOrvVRfXxeaAGgEdyYqfAauogG' +
  'OnnNoOAaekdmMDZzgGFjJVvoqQOtDdTjJqkKQqdWqizzZNkKiQqInZIQLlomwlKkwUuWuUGiUvVTtXxR' +
  'WwEnRrNrRSxyPrRmoOQamVpPvyYRrQqIzsSZeEivVlUuvVaVdDvAaApXxFyIiYWLlZzEepAaPRMJTgGt' +
  'wWUujGVvgawWKjJsSMpcCPLlfFGgtdskHhyYzWfFdCcAaTLpPcBbCeEOjhaAgGHpPtRrLaCvVcPbXOOC' +
  'cZxpPXgrMmRXxGCczpRrPGCcWCCcnEeNncCbBahHQqAVSsvlYDdBeEZzQqJvluUrRoSsOPpZzHhgGgqN' +
  'DdpYFfNnytaAjJflLuUsSyQkmMKPpqhHsFPpJSFcWwCUbBYyrRrjDdhHFffQqbUulfFtNrtTYRrymIiB' +
  'xXZzGgTtbBUubMRXZXxZzzaAfQgGKdCcDHhJjXMmxIWwixhjJMmlLMzZVJrRCcdDGNgGnsSMQqbBmTcW' +
  'VHhmMvQRcCrNaAIiNnuUFfLlLqQiIlQtBbhORrFnxXNKkOrRmtTlTWwvVtSsgDGgFXxfwWdLFfmeEHhV' +
  'GsSWtTSseDdOoyYEVdDvNcvVCiPpddDDVvPxXOoqQHhcXxyuaAwWMNnmTKkfPcCiwWzZzbOoXXQqOoxb' +
  'HmMuUmMsEecZawOjJaSshPprRHVAeEaPKdDkKkPpKkiIKAbBqQnNgnNGKWwGgFLlVYyvIifMuUmiIJjf' +
  'DoOxXJrxeEXaAtTEkKekVvGgLlOyChmZeEzCLlccNnCTeNnEgUyYuEeGGvnNnNnNrIFyYVvSWAawhgdE' +
  'eDGiIPSspxGgUWwABrKkRIiqQLlbawWLDkKdZzuUHhUuloaAkKwWKkOzZWoKkOdDyYFfMmhHAadDsCDd' +
  'VEevcvVIiSerRMmEjJdUuLuUzZdDzuUqNggGwYVeEvVtcWwheEXxHCiIcCfFTDdkVvIPzzZnGgBuCcRo' +
  'BbQTtZbGgqAaQBWwzaAEDdeZzfFvVeVsSVvvEYCcmuvVVubBUtTZHQSkKmrRfLlRrEeKwWZzBLBbtTlb' +
  'dDzHTlLnVBbvBVvZiKqPcCpMCSsPpZFnNfzfFkKhxFYyfVvMkKmjSVvVviIEgvViIzZXxXxuAOppPPjv' +
  'cCVJrUUJjuqQuoOcwaAgGdDKkUuRqQJjrWtqQWwopSsPsSOSsVWjJNxgwWGfIiAaDlaatTAALyqelLEQ' +
  'iIiIjSBbsuWwUTtQvVqLlftSsHSIilLTVvYnNuUrzRGkKTtgrggJfFLrbBHhWbGqQaAgHhbBlyXxYYdD' +
  'LtTpFrRfTtIiPeUuEsWwwWrIWwicCiCPnwFiIFftyYTZzFfSCDdzZpeHhbISLlsiBxpPXJbAarRIiDdB' +
  'LlFhAaOaNIeEDdiDdjgGTtdDpcCLBbdDHjByYbJDHhAadFfQNnqtTeEhfFrRRriIVvfsSFfGgDdDdpPC' +
  'coepPBbEUGggGbaATPpNntwWoCFfcgGOmYtTlWwgGiIOtyoOojRXpusAaSNSsnlibKQqzgGZkIiGVvgB' +
  'IcCBbLjJuUvVuuUhIinIkKOooOigGGgskjTUVsIOoCciJBbNntbDMVvFfWQqwxXeEGTtDdUwWuCcpPgM' +
  'mMmPwphJtTbBNnCMmIimRroMmFfkcyBbUudDYCdRRVvIVviwgKkYyAavXxIiIiGgrRmMIaATteVvqAas' +
  'TtOoxflwWOojJEafFWCcuLlOpiOiILzYPpTDdQIiEqyYPpbVbBjJZzvnzcgGCEeAlLUpJjdDNNnnFRXO' +
  'oRrxvkKguULlGATBbzkKkKPVmqtTKkdDQqTtLUdFfJWeEquUOKkoQqBbJLhnAJjaNRrHgMsSmEePNiIn' +
  'acxXQbBLleQiIOoDkKdaAeWKkwBbLlUNnDdJjukSsPWwQqpuVKKgGHHhfFmMhNnkVbBvkOocChHYxNBl' +
  'LEANfFAFfTaAtCcnyXrRkKPOopxnNtTELleYnNiIRqqQgBbqQsSrRxXtQXxqlkKnNmaHhAtTeEzqQZoo' +
  'MmstyfFYLcCpPaAEoOeocCAIiWwbBcpumMUbQdDTtAvVwBtTbWYeEasSJrPptTLlRvhHDDMmeEitTEzZ' +
  'DtgGjJeXnNvjPxXQwZzWrWwjdaaGggGAotkKklnNQqdLlwWtTDEeLcCprRJjYaspPSHhhHxvVvswWaqE' +
  'eQktjJWwdDfFgDdGxniINTrRtPpICcNclLWwoOSKfwGGjJXxgfWfJAaAajsSsDdSFwlJjLFAaiIdOxtT' +
  'XWVvwyjJYuzRrZtTOvhQqtDdgGJjCcLllWUVvnNAadqQgLcuKMsSmAakKkrkKjJRnijHhxXJWwOdDSsx' +
  'XRrPLpPOyYCOOoeokcCGgIiFfKnNOXYxsSXSsqQHoOsGPpgnyYBbdDbCcBpHQqtPVvptfFnNdDNuDMGN' +
  'ngVvvVXVdDvLlhHVWoOzvWJjAawGvVgPTtwWdCcDvCcVpuqQrRrTVkbPJjJjkZNSsnQuVplLEegGiPdD' +
  'pKUuBbkZtTzcCxXDdWAklvVLpjJLlgGPAGgaNnmoOCLlMmGgUuYOhHoynNOoyXEefBwdDCcbBOosSDdW' +
  'HhbRjtTVvLLvVbBmMWoIiKaAfaAkKUYxXybBHZzGDdgHnJjGZUNCcCmDUtMmTtGgLYEeyEelvFfVoeEt' +
  'gnJbBjbBPpNkKZKkpoyyYlKkdhqoOQHDKaJqQLlxaAFhHfiIJjpPDulLOdufFUDEedYZkoOJehBbvtYy' +
  'TUuFihHIsoUOoubKkBWuUwNSvAakOIioriIUHBikrlLRfFFfEeJjUujJKNYNhHnyxXwTcOxmLBbrTiQw' +
  'WmjrRJClzzouUPSjqQKkzZZzLlfdDFpPJQqHUuOGgohdDXwWxgNYykKeQzZtTqzhwsSWnNffFwWvcVnN' +
  'FfvsSsmOgGeohLpBbLlkfFKKjRrJkJjiIEenycrRYyCYkKzZoyYcCOCcRrOJJnXVdOdZIQqHDdlpAZza' +
  'yLlYWPpjJPpAawMmRcCrEejYtuURrVLVIvdTjJtEOoearRkRrouUAatTdOVyUuOoPsSgGDdptPqUuvVr' +
  'JjRQMmyYfbwWBhHEesSYVvXxLlOGnNnVWfWwIijJiIFwaHDscCSUmcCyYdDTqQttTHhhqQuUsSgFieEC' +
  'pFfPFfSswTtWSdFfDJQvVqzrbvoJjOmMVongGCcTtCbnNJFszZlLnVvYzZyvVkZwWSsAkCcfmepqQPxX' +
  'xQVXbmuUMazbyYyzjXxJxXtTTtZUeEuHRrCcepPNwWPpnmdJjyYstTYywpLZXxBbzZQAaqOoLlhYyfWw' +
  'zZYydqWLXxAjJEvVebrRlQqdvQNppPPcMmzZgGOmMZZzzFyUuYfGzWwevVECLeElQaARWrwWSpjIiPpO' +
  'oEeJcGGAfFWKkwLPplapPVysNnKkIKkzZcvVutThhMmvnqQdGgDfFXuQQwaCcnkHhKDdNqQIiHhArRuV' +
  'vwUuWtTxHhXMNYkwvVeEkMNIinGLlgbBzUnNuZWuUTtoQMmcqpEtTwnNGgvwWheEVvxWjvYyMNnBMmBb' +
  'LlbFfXRrZqgnNxkuCcsvVgLwLBblvoMHhmOSsVXgWVvmMoOKPpOUMaAfzZGcCgvCcUuBiIBbzKNPpnsl' +
  'LSHhUrGKQNnNNnuUnjMmJXxYyaIiAqYUuuUeEaMmJZzjcDrzNnZSbBgGsOoBbaAfFMsSsqNnlQwEebBm' +
  'hvVSsHkTtLloVvaAxXGOoFJWwsSMoIcrReYSDdALlaIaPngPoSONBxIZziDUJjUUucDdDdTAaiRrvVIt' +
  'IUAajzsSZKnNkJuiIjnddDDNUrTHhGfFJOocCMmXxcCOpvVlLMpPPzqhqwWQsoRrzZXvVRXFfxuUMmSs' +
  'SsIrRcCQqXRujJeHhESFfYqEeAaRrKkQyADdaJjPplRNnitTIKkxOoDdDdXrngVruURBbZcgGVvCQqkK' +
  'zHhvVQpAaEeaArXxuUdDEeRGSstbdDMLloAaOgGAVEevKQqkvVsDdSzZBboOTmMtkcCKmwmMWMlklLbJ' +
  'NnOohTtHjuUkkvVtpPyXpPxTwWpbVSzZqQYBbgGhpmcChHRpPZYYycCRrxXQujaAmfJjFMpPIBbqiIGg' +
  'yjyYRrJpSmMsPQegQqGXWwxtTBnFAafdlXHhAlafdUtAZzlEewaADEeyQqYgNnqHClLWvVqDdGgiQRrq' +
  'EzzugGeqQHOcCkKvVdQkKkTtEeyUuJLOoIilLXxlpNnnNbBPVwhwXrRaARrjHSsryxXzflLFCcooOjQq' +
  'JHhzVioXOoMmxTtSsCyQqIdDnVvWKkwNPprRiKtTXWwPsuNnVKCcTPptkMmVrSsqQRqQoZzPpOQqdovb' +
  'BSHhXqUuoOsfaAObZzBoYyFTtpPxXdiWLlwTsSkKWHAajKPRpzFfXxZPrFvVlLjJEQlLcCHhVvIzZiSI' +
  'igGTBbLlZsSzthXxHlLCJumMYyWrgGRjJwRrnNGgtTuUMPiIpNOoisSHTLlxXvylCDuUcMTtXxKbHhsF' +
  'GQqkbBMmGggGGgnNZztUuBbTbtKkTSsoSNnnaYwWidwWWwDimMVvIFfyYiIkDdKNJjOoMmRrHjGgnNnN' +
  'yoOTtAaaQqAmMuUDTaAGgQBbvbnLlPfmMYyyYQqwWFeyYdDDofFOdDJjiIKrThHEetEloOEeLlaVTCrc' +
  'aACaOoVtjJVvQbBpPyjJjJgGoVveWSsOfchHCPUuoAkKaRrtrriIRSsjLjJoOOKkoZbBYadjOoBcZzCK' +
  'kbJSvVsxXqDZzdrRQMzvVZoqQNnOmDrDhHGnRrvVKrRviIVAAzIHhgSXxNnyHEPjJpErfFAbNnoaZieE' +
  'zWRmMrwRrZpPIQBACcUrKkKkrRRoNnZCcMyYckKCmaAJjvVdPphHDzXDEePbGgtGgXOoEesEfFmMeqQs' +
  'AidXwOQbWrhByYTzZqQDdbElLeBEpCIHfZRrYyRGxXeTuUVvBbfmMFVeEYxACvTpPIitjTvVaAtjxCWw' +
  'YPCcSsMKkIsiInUufngGGgNJjFfaAQqPphnXdiINkKnrRIWoOwuUVaAaViIpPTtwWvDEHheUNnQZzfFb' +
  'BKkAaTtLlBGQqzxXUboOBEqgGZUvGAWwsdDSsUeopDdJoheyAadwhJkKZzKkjyUrRrvBbVREHaAtTesj' +
  'WguAciDdIPzInDdzZNhpCASsaMoOIYyekZbzjJZrFflLRKxLLIiWwCcQqTtAaypPSXwWnQkKVvDaAdxX' +
  'aflcFfCGMmTdmMaAzZjqsDdmAxXrRmMSICGgmvVMGzxXoOoOrpPbNnQqAXTrnAuWwJSsPumMeEiCcwes' +
  'STFfDAHhNYyCcKLlSsIiuLUcCulUkNFflJRrHhpPmLlgGDlLvVFfvVCdDcrRIiHWwVvymHHoJjLIGOEe' +
  'ivkKURrJlOoLmMrRgGUCFfamdDMfFCPpLlrMmRrRJjcWweEpAabVvBiIhlLHbJjBDdvuUVvhfkKWAaoo' +
  'OOoOcCeZYyuwEeiTtPpIWUtTdJjzZNqVaaAaALgGeElSSsgBbgGuUiIFdDQqJjUdYKiBcHwWOVvsSikV' +
  'eFKmVLKhHksSdkKkZvkKdDxHpPhaAKbBGgDbGgBYrRrRvaAVyHvaAVygDdvlLRrcCnNVNnEedDKRkKrd' +
  'DWuOvGgjzdxknxXFfxXXjJVvokKhjJrRCYODdouhKkHwbBWHvVhPAXmjVjvPpVlLPCcoXxOQqprVvaPp' +
  'AGgeXTWlHhEekmNtzZfAapEHheilQhcnNzZszZsSkKbRoVvQqqzZQOAMmSZzslhOBbLsSrCaivVIAcrX' +
  'jNnHVVvQwWHhqQkKNLeUoOucCEdDIhHilMnnedEexXxilLHoOhInNhHHPppNAJjLZzGzIukKBbdDGgbk' +
  'pxvVXuUDeEdbEeBmUuEhHeMPhgGTAAjCWMuFjMQqmJPWwAaWwpwRJjRrjeEXmMrRxJPpTQMjzpkKMliv' +
  'VhHkKkKkcCLyIQBbSsnNqafeXcCwWDBbTtURSVOoVhHvXEEaAOUuoeHmLiIeElJaZLUuACcyBbhKhbtw' +
  'WrUQqeaAGEeFfgZzzZWympyYeCtTPgcCtTxvoOVTFFRrffuFwWaxXdYrRkIvLlYyVcuUCiUuKsjJHhTt' +
  'AaIbYCcyPqoOQlAEsJjjAKkaCSTBVLLTtjJCcMmllwWOIijJaFfrpPRMaAwVrQqXgGxCkKgGThHthlLg' +
  'GHGWiIDiILJlFgGIhdbUuqQBeOoGgEkzZKDGpPOopPJXNBQmhIgGKhIwWbbMYsSMbWwTVIiTtEYCcedD' +
  'EyDdYPKLHhlLstSsTtOxXEebBoeFfIitTOKmMkpJrPxXEexXOXZunnsSNrzuiNbIiBQqNnbThHsluUQz' +
  'EqKyYkyxQnUFfjJkiuqzZQqQkDEKkebqQEeSiIBbMmsBctwjgVvMmgGKMryBWsCcRbubLlBOoawWApDR' +
  'rKkjJyYsKXxkPhHpbkMmSAlHFfFSMYFftDdoKkwuUWeZKkUrRukuZJSTtiUkKuiIIkKHlFkTtKHoOfFH' +
  'ZzKdSkwNzuUZnSsmCmMcMXxZUuzNnGoOgbBBbkSsoOYlLykKgvbBVUsSuLOWwoUulHhqQFRrLtnNTlWd' +
  'XEexYyhnNVvPpMJjmPpaLotTODzWEUsSDZzdueaWlRHxlwMhHmFQqhJhHbIiZzxXSQgGFlLKpPdDkfcf' +
  'EeFtMxUbBHhuZYyIicavmrRRrpTtzZzyrmMRvZeLuUJHpKkcfVvZDdKkzFTtxXpPCRIiPIUuGgiqQIjE' +
  'UdDBbuUzKkZueWwVlLWwoJodoaeRIAQGAagaAOprRPoYWTtmseEdMmlLoORjJcCrlLDvVLlWOPsNnNVv' +
  'nEhjnNMTECrihEeHDQEebhKbBXiIxgGgXOgGrRNMmrlLRtuUTFSDdsyfFYZzBAsSyYiBzuUKkZbQqdlL' +
  'DlJOoMUkKuGgwWmyBSlLHhbBIzsLlvVxXScNeEprRkKxXRrveVvwJjiJjnMNKkawHrpCzZPprcCgqeEj' +
  'JUGgmAnYyCIicQqNbRkWkOqgGWwhHUwWupNnEePPhHpQeEzPpWKkBPpFfAabvIGgSkKbBCTbBwfFWsSk' +
  'KXxzmtFIcCiPRrVgwWGvpGjwWJPcCOTiOomSfFMmdDEeaAyaAuOoNNQqFkqnPpMebHiIisRrSTDYydas' +
  'vXxVIKkHxlGgLiIiCcIEKkLlekKDdHbRrMBTtksBbSCAUuafFDABbaxXFDddSsvmMQoOqzZQbBrvEeVr' +
  'LlPmDrRdMnFJjfDdbRrBjmYkVvvvIiSsVVacCKGgkFfYyeEvvVMGhWiISstCcToPmMRrpHhOvRrFdPDQ' +
  'OdyVvYJZtMeDNnZTtaHIiTtTZoOaZTgjExCcXeIydGUuKoAMhKkVfwCkCcsSKcHzXxZyUuXjJiIxtZxu' +
  'yXxEGgxHhtTmMLlToPJuHePjSaJgSgrUulLvVRfUmvVgTtGMXxGPpgwBbVwEensmzZSMCcmpgGPTjJKs' +
  'fGXGgxuUrRbWwBlLCaAqQTdDEetXxgGRrJiuUIvVOrcCoOzZbrxXRIIifFqQKaqQAtRoOgKQOWwbBuUT' +
  'GgMWMxXmuURCeEcWwrcCGxpZzXNnxwkJjMmgLTtqQSWdUulhJuUjHLfFosWwkUVhHvehAaHjJEhbIuUe' +
  'EEsapUoOLkjIiJyYbBYgdDHaMfyUvnNXEfFNwWPfnRhtmwWqyRrYnNjOEWCrRcVgGqQJQIixwWVvmfFM' +
  'vVQHhAafKyaCNKknQQBbMzGXuUxglLUeusbBSUFaAZPhhxQqfyYttCJgGiItTjPhHeEMkKdDlqQerRuv' +
  'uUilRIiQqrVqkKUulwWwWGXvMiImfFWiUuBEeZzbaAnNIUsMmzZmMSnrKkRGPjdDJCcpguUSsdiAaIlL' +
  'wWXTqXnNAajZFfXxUnIRqyoOEeXtZTLltEecMcCmMmzmMaAZCWvtTwahexMVvDLVKkvmgyjJZqiIQUIi' +
  'uOoUuzYoOHxfzqwWZiILMmlTIikZegGEmMhHPpgBdZsSzIbBVvWwfFiiIOoYyoNmMxXgJjXgeEZEegZU' +
  'uClLcFWjYvVxXycCHGoOgGNaUudwWDSNnbtTzpPBbZFfPprgbhHhlLHVQfsBjhFfMmHSsNndRrMyYTKo' +
  'OZzkzBPptTbDwJaAZzdDJDVhMNnmHBfsEiIeXXxxSFAabSUQqusvhDdxXtTCReELldLlFViIWUkKPpuX' +
  'mxBbXMkKtXxkRrKTMiIeEPDadEeNnUthHwWUHlbBECpVvqQPFfrRcHhvgHhRESsOSgrRGJCiIlLcBbyY' +
  'JjYSsyrubBbBQqghgGzlLZbBVlaunqQrRNUAIiEeWReWEegGiTtIYyxRRrRrrEunlLIiaaQOowiMVlLv' +
  'FMmDSsQqdiIWwWwbBNnZzvVBbdaOpPUuoKkcChCuiIUqsKvoOVxyWowmnSsjJHlTStVvltTowNRIinaM' +
  'mQXxNIolnNLWDdwlbBZLlzMmkKRgGrREejOjJrPpNnRJjbAcRsNQcCynNYcpVvFTqQuVaADORfEKddzL' +
  'laAPCHhspPbfFlLhHCbBLlEfFemISmMAviIdtCcoOIAaiTDnfJjiIlEJboOaAJASshHGgajQLeEoOlLE' +
  'eFfEDdOocCoOYUCeEfdDYBbOYyVvyYcCiQKkxXduUDqroORtGIiDxXyZWHhCdjJdDrFfHUoOqDLaHhWl' +
  'cCWSEesFVviIiXxYFZFfzWcgGajJAGxcOolLQqjJvvuZzieEIbtTOGAbBadCjCclLNZwkKwhhYuQqejW' +
  'CcPdyYhHHwRFfUOWwDUuqQdDqQfFgktTKGMdWluSSshYKpPYyGmXAaeUuVkleEGgBbVvhMmgLTsyYeEr' +
  'jtTJRpHcoYbwJFHlLmNmmcfFqyJOZyGxXaAgEMJrKBBOgRcCNnLqkKmMjPTtWjXxMQqwdDFFwkiIwWBH' +
  'hJjbSvRrfCcFVkKVvFjypMmqQPUgBbFbMmBWmZjOoJYjJPpyzmMMAOIiojWJhdDDdlLytwWTTHhEetYx' +
  'XoNpPzZPWvbYBwcdDnZoZuIaaWAakKKNQWSswhFbtTPpHKkiDdIfFhPpKEOoXxeGNpPNLlpyhnEmMeNd' +
  'CRrDEeHjJauOCcCcxXooxCKkzTteEjeEmtsSUaAQqunNTXxMauczZfFXxrQDlkKzTGtTYccrRzZHvVhK' +
  'dDkMSsEWRmMnUzcCeEgFeEfgGdKWUuVvwqXRrykYeEBbgGCDyYBWospPSHJjKUubaARPoOphtfFTfXeS' +
  'AxLliuUIgGbBzEehCcHEeFIXjTlJjgpPGgghibfwEmLloiZJjzCiICSslhHfPpROMXaHCliISssSWAlv' +
  'kKqQyMnEeYkHbvVpQVvYyQqMmTkKznWwXxgAaGaAqcbBCdOuhHxewuoIiuUQqpAaRpPTtXkRrKdpZzRc' +
  'HbBZpOoctTCfxhHXKTtavVNqYSVvJvVjdDvUhJenNLDdrRfxdDxbBXXKdyLLlYDtgeBbEQsnNbYrRypL' +
  'lPBSqUhnbnNBNiTtYuwjgeYJJnNyYWntpPTCYycOoNVlznNZLebSnNsJjBNneQoFDwbBWjYfFRrFfyJR' +
  'sjJTtSkBhnWZvKklLjJGwWdQqTDdvVbMjJmPrRbDdxZzXBpgdDqAaDUvkjFxXfSsJWXgaNnOoTokKsqQ' +
  'SOtApzZeBBbMnpQIVvpzeDMWEeshHhBhyYFfwWWdigGDdwWGmQpqQcvMRxrRzPpZgGVGgqbNcHrrRSyY' +
  'sRSsxSsWgGwmVYyEziNndZzGqQfmpeXCgYdofFVvcvVVmSsMuqQnNUKkhHuUcCJjxXPcCpZaAzvIiKrj' +
  'JgeElhHUeEHhHhBbJPlLpWPmAjHhkHhZIgLAyYaBWkBqQHoOeWNgmMNUSsmqvQvOoVaAlSsgItuMVvDr' +
  'XPpPmtTrkiIVAQIbqEshRVdkyYiltTLOoFpPUDdzhBwfVJPWwMKkxubBqvORrwWocaLrjdfvjGMsSXxm' +
  'gUeDdYuRmIiyYcFJjDXknmHOXnNWWQRrAgzBxbgsnNMCPpoklwWYFfGcCGuUmNzmHsOotyvVUfQqZzxM' +
  'jGhHgAWOowSPFXRhQqHhHRruNJjnjJxJjXuUwWyodjJihHImhBgGpvBZzxPPapPlLmkwWaAJqnGghlYy' +
  'RDdaLDdmMlpuGXxmMgGRZzSshwIiWoyXaAsEsjFXxMqaPKkhGsxKIioOwVvECbxMRFfrkhpeqQITtcCA' +
  'OfiIulOoLndwYrAbqcCEYvVyeYynrhJjOoiKkIHskVUUZzEeDdHhUhVvHHZzhNyMWdSIisDDdwmZnxXR' +
  'NnvShHVdrqbrnfKlLcFfCksSGgUufvpPlwWLmmMRqPpbbvMmXTtxshHnfFPWwZnqFfQjGOCcpgGBpiIP' +
  'bDdIiwTQSLYCxugjaJgGfxSGrGIibBYmMcCHaMgSvVegWsBrREmLlMEeWwBKkSsLleGuUIidkxZQqzTH' +
  'GQqJKUuyzFLlfFWwPenFZznntTWjEerJjxXGgrRSsvVJRrjxBtTbuHATtWwsNdDHhXSqbaAQMyJcItcM' +
  'XhAaOKaAWzFgNkCcfVNBbbWIbADCqvDxGhmMHjclLHMmdwKcCAFSsRrHhfKkaBHheeEnNYYkLlvTGUOo' +
  'JjmSsOIRrNNnnbMDdZsVEeFJHhYycnZggGGrHhGgEoOvjUxOgZXYrNePpPpMTsSKkoaHRfFMiImBbhHN' +
  'TyYSkKaNGgiYyegGTtnNlPpnNjVHNnGghzVHhvZeENmsYxcCaAwWqjJQqnNQqgGQwrrRrXLqQlwCTtcG' +
  'yDCcVZTmMkXxrRDIiGguIilLVsSvmMuUDrqQLlKkRwhHXUtTmMLlDTqnOnNkWwWYCRmMeOeEvVoFawiI' +
  'bdgGuKIXokEPuNnKkHeErLTDdtZzhsSHBluUqSstKkgBtTaqFfkVpxXtaBVXRPbPpdgvmMVfOoyYNnWw' +
  'eiIfFEwWLlVvBNcjetdDTAaLlbAaBvVAMvVmFiLwuYGwlpTtRroOsCOocnNSkQoppPThGZTLHwWIZOoS' +
  'frRFkGgFcCfnNKoOoQqudDwiIcCKRiInDDPpzZrZxXUugGzVRrYZzcLeEcCVvLAaEMYMmvRVvKkMmLpc' +
  'xKBbkDdXpPGgCOoyYPgGOaAoWoaAOaUVvGsuWBbwawEeDNyGomLFfbEeBdjJClOOPplfMQZFnNwlvDIE' +
  'IiGymMYgDaAtRrYgeEGyeRxXrKkRQIJrPNBbJjniKBCnpPgGNwEtmMsSWwdDGiLlfFEilefRloOaBjhB' +
  'eLaADdHuUhnyIGNZFawFCpxTtmCcMjSjTttaFfpnzUgaZznXdDLlcDwWcrgoOOcrXoKbSVKLLtdmMsSl' +
  'jSXSsxtEeiQNDTtdwFfXxuUwZaAtTCLnPpDdNlfkYyzZdDDdKFEeAuUSsltBbTqdHpjBUuQqbUumMMmJ' +
  'TtVNOfzGgtGuqgJcCGgjGCctRgGmMzZpsSAROolbBaALHMZYMmyagxpfjJAnvTvYyAYBbjvMwWmBbRHh' +
  'rIuhHhlqoODzorXMETZbBLwWlhmMlrmMloOLPpOQItPpSsJjAfFCcUuBbauGYpArSshwRrzHntRDEQqk' +
  'zvziFQObhPHhsSGTcSUhBbdXxDesOieDHFDmqEeklVvrMtzYEeyZTHYyNnhxdkAqJCcIMmiHMmuUfFbB' +
  'OYhHiXEuBKqQCrQqBbRlMWHIiUCcAkTtPRDduuUcyZzEeCVvMeEGZfFNhGuUgHnpgzjTtxlLXCCIwnFf' +
  'RBJcCjxXGgJkNLozzoOgGZrJhHJFciqHBupeNlLGPpiIgnaAHPjPTXxvVtGSsTtsSNwWFUuqGgwWACLl' +
  'cUutBPpPzYWqCBiIDvNoYEeyAaRuUTtaAKKzgXwmpEeaAPuaXxAtfFdDYmMyaqQATzqbeEBQKINdqFfB' +
  'AQqakKxpPBqeXxblLLlTtdDdDdeeElYvhHtukGgvVGAaJjImRramHhWsSwcCMHhNnlnJIiGgjPVKoDGb' +
  'zRrGgyYyrIiMJjVXvroprRSKUuqylLYYdDDEzVzZEevAjkKjJMOcBAnNRNhHLlyYZfXuAHZzxIilRrND' +
  'eEUCRfiIrWfDdLlFCDdcbdtTlHCbByxIghkiEFaqqvVQQviIVPpBneqQELlDsStTdqZmWpEixDZAxAaz' +
  'SrRyPzNGgbdjhQqfvFfxXTrZzRMmaIiAVOJpPjoHXxqQhvJjTMDKbkMiItTmZyOopPWwlLqbxBbnNkmS' +
  'sYyOkKhaIBZyXxXSAaORrmMbYGgyGAahmIpCcEBmJjxKkBbeSpUDyTtSdDFyYXxfOqVIquoFfpoOEIiW' +
  'qmvCJSLQqltTyIifdDywMmlxXquaSuUUlLwVdDGOHBbbgFXxhkyIGllLNxDdnNYwpPsSWHhRwWjJuUmM' +
  'uUunNUOyRQpPoObBOCPWxgGXLKkKgsSszZSGklKTtUuilYylLcsSkGoOnrRFrtTlfeOTtxXGgXsPpJaq' +
  'OoehbbBBHolnuUcpYywkwWYBbspYVnkwhHitsoOfmbBqeIwAuLlrXZOoOofwWnZjJDIkqiRlzVvxCnNf' +
  'FiIcXGgsbBUuSZPBbQqIigFwWcmQYPpqgAPxXIBbgkQqEAnNwWnbBdVvDigGTtXBbfbwIGBbIQDxmuZz' +
  'SsSFfnNABbPpqgFTqzZEfFdDhwcHyQdWwboAaAeEMmeEUpusywUKAaFfhcCzZzZLlRslLSeEhGpBbJNG' +
  'hUbBuHtnNTGkmMvZzJlHUJjdDuhBbuTtDzZnNdbXQfIuvXAIiaxnwWWLiIyYlejQMwFfhPfFuUSxAOoz' +
  'qYLGSPUuBqXxoONnTtUQqBbBbuqVsSpIivGQkGLlqQHcCTFftwAMvumZJjQzjmSyeEHhTwsSWwTtTmLj' +
  'JaWpwWgxXgvDddbNQYWGggFcCfKMzuBjmMJbXTtxudezaHoOhAuGgUJsSjGgqLlICcwfFwWxyYqVvPpX' +
  'MnNQQTtdPpLPpvMmjJOocCOLsVvxXMmPMvLlVUXWEMTtmGgHheVgGxDUSfjJTbfdwIeysUsnLXgeEhHW' +
  'DdwKVHaAhRrOfFZvheBpPbHsuYyeaAsVxXFQgGPHARzUuZVvrEeahlgPgjsDNnTuUlLsKkkgKaSMmERr' +
  'UTtrhnFbBsSfMxXYEJcNnAayfVdVxXjSFcCRrMNnEeGzZSQfDdaAHhuUFUuEeJjJsShHSvVsxJXRJNdV' +
  'vVygQyIiSZzcrdDtQenfZBWwQqkKJjbhRszZcnNCgRrzZoaACHhqWngoiIOotDVbBeYpSsPnNoOyEFfV' +
  'zlLHhuUCcZGHhDVvvhMmFfHqQDdoOdDMHIUEedzNsWvVvVPRqxXQExiLqQYWwjrizBAaVvxXOitKuqKv' +
  'UBJbwWmrRMbBBuynNnvwWqGjNyYbWwNFcyJjuaAUjJbrRUbzZbTGgZZluIXxiUICkKufFdJiIjwcNzlR' +
  'rqEegGEZzSsAlLaYFPeEhFTcekGgKKLgGliIpPHiMmIWwyXxYiYyxUHNIDZzdRDdSPpMmsrwDgDdzZgO' +
  'vHOjvOouepPoSwtTJyIPBopPVrRzZrRwWVvYyOlHPpIiNqwWVvQeaaeEhoOeMTtFuUYAaJjdfSNnBbSi' +
  'tCuUHhcKhUMmEeuvgGsITXQTdDtJjqehaoZChLkKKdjJaALnQqPJjHuEtDcWwkNQWCcwqYylLnAJiIkK' +
  'ktTKonMxtnNmewywCVLTkAaKLlNdfhHebnNaNcIpPyYWgfgrRKjFwWWwtTLJSsOooOlNsDsDdBdYfFDd' +
  'ygAeEwWBiSwZEeQrGgfXWxVvuUgIAVvWDbBdwEeiQzZKgGihQEtYhowcCyYWOuggyghcQsUvoOwGgFfW' +
  'eEuiIpdCcCUocjJOqQMTZbmvrAtiNwOxXvVYyoLdDlIxTjBbKDvEuopPqToYfFPYiIHhoNnNQbCbBNDd' +
  'MOUKkuoiurGgUuBCcbhaToOybBYRoLpnLlRkzZDMvoOPAPOowvVHhuPpgifoMxyxqSkTRrQPpqRryqCp' +
  'dyWwIipymaurbBTcoOPpWwFkKQqIgNnsMSsBbNnsTtSOpJjStTGLbTtBbBDghaAycRTGiFTvgNAalLzZ' +
  'svaAiIDIXsrRwMRrxqQTtTnNtcOrlyQHhqgvwWxXxXbCcMmoxhHXlLODdSkRZQSsqzXmMjJFuUsfXxiq' +
  'QStdcClLHHJrmtTpHtTaOoAHiIPOiKkKxXkZzueyIebBQJjquEmmUilyrRYIgxcBbUAaElLlOoHhuzLL' +
  'lAawQceGkKudDUyxXqQYjJCOAmdDMLlaYCoavCVhpPHaArHpPKxXKkTtOjJocFfAaLmaAZVYypxXInxa' +
  'AWwwProqULlubvnNHhAaVrRBNQnCNnZzOEGCyYhsSHmLlMmhgeKjxLhzRLeFfkPpEDXmMrNCeSlaLlAL' +
  'hHstjJTbBqXxQEcqfnBbTtGUkKPpnFwwWoOnAaOykKYKOAnkKNSsHCmMcFbjyjOoJrcebzZJcAnQUuxq' +
  'dDcOjSKzZrPqQXxnNoPEevMUuqQAaBxCPDdpKkErFSQSZztjJZzaATnNeEzZmplgcOoIilLJUujZzCSs' +
  'GRranDUdnhxXHpPXifxMnacGgBqPpZUPpsDdCMbqThHvVnKBSsbdDlLRKkrpOoGOnfOoGgDjJoTGrkps' +
  'SPXyYJcCweEHvwKkWIfFizqQZvVFBNnbfWTFpPvQwjNAauUjyRrSxTnoOTtwtGWwiyYcaACIgyYuCJjd' +
  'rRkKSJjwcCQjNnxbJjtTmpcCZoOcCziyfFFEfFHheGaplohkxXiIORRrqURdpPRJmMtTwLIiBbDcFBwU' +
  'raARYPTvVlGxcrqQqrROuooOHuUhunjJGgXoPorIkahhnNHEqAajJmcCkKyOMmobjVvYiepOhHbBbItz' +
  'iwGjyYAavVzzZomMlLwEoOpBDOoXldmMDjgSYbLlBGDwPtPnUKkukbdhASsmMSLciIsjtzIyzgsSHhds' +
  'SDZcAatTAYsVYTgEUvQlqzyZkKJJAiIxXaUaACcCzZNncutZvvVVzhHwWpPhHTjjDdtTzpPuVvVbezLI' +
  'iWmPPqRbkDsylBbmMmMHcEgTxXLZzTpyYIULlTtMVNhHkuUReErkdDysZvvVkxXIxXiGgGSfmwJIRsNB' +
  'GgeEjNyYmZzRrbFIifFMmcCLlpWSgDdfFcZwWNVUvBFpPbfwPTacgAgXxGCceHJABFfVPpvqUNUZJjSs' +
  'zumTtDBwiIWJjbBrWMwnNEqQIDcnfaJWDyYgkIxzAyYaSIeJjxqQqGgQiIdHhtFfFbBoyhHYYhwtbBAe' +
  'EKnyAlVBjJtvVrhjJvzIoOxPeSuPTaSHYvKkJjLlWRrJhgFTQjkFtTADizGNiTQLXRrxwuUNEebBkjJJ' +
  'jcJKjgZPWTgDRHJlLBFZzfOlIjjbzZgTovIiWPOQmMCcrRuPGgSsCTtFDdfnNHcIScAwTGcQSkXXxqQx' +
  'bBKKIRDVSkxwlYyUCqXxsSAuUWwwPswWcNMKkUVpKwTtOoxUFWZDjJgbSKJNVvzsAsftTCdeiIEDeOoU' +
  'jJuZLtTwWkKlLokJjLlcBNLPgFAaKAayODjAtLlYyzQPpguDMceEeCiXIJQhXjJIZfLZMzZPkWIVviwW' +
  'RrhPpSscCQdjJqQDuqerRFylbBBOoUuHmmGYkNmMNnfEmKjNntXxXxBBbsMDdRrdFfDVhdWIDdaARreK' +
  'kiPpDdExUdisNnXJjeEdtGkThrDWfFPpuSWmMmMEeSeODVvEeohgBWTTthjnxKIibhmCcHdBbbmaABbC' +
  'xSirRaAcYdDVirRjJIcCqiwlOeEAbBarazvAlLoaVmMvAQvfFITtPWwpiAmMafUurRFkFoTybkKdZJEw' +
  'ioOtsftdQclSLbxXRCsUamqhEegiQnTgGtbbSKWwsMmhdDObBEHhqWsShbvXpfkKAkKvGgvlLjmnNMZr' +
  'RlLCcQuUqNDPpgpPIoJjjxXCcFfPEOvZzOovXpcCMdhHvVDlqeYyhTrxHiLDUiIuTVfEEeuEeeimMIFT' +
  'RriIAqIBHnNvmMSictXxTsDdNAmxXWqxXmMmRrdfaHdrKkxFMezZggUujJmajzmkNsvVSnSsSrRjvZov' +
  'ZCioCkYAprPpmwUuJTyHbBvVpPVdDDdVMDdmLppcgGCjpCxrlOIAaicCNyNcpGizeVviGGOHhtHyKkLv' +
  'yYiItskKqnNxXQNkCCdKRrJlLyWzZyxXYpgcaAlhHhGGHWwhwemMedmcxGnbBNfFBYrnQqqQauUDdAhC' +
  'FRxWPdkOHhoXkKDujctoOChHJnNuUuFxUNEeCjJymMFiYyrdVaWwBbAAbBYzewvfFszgFfGwdKfpbIiM' +
  'GggBzZiIEdeXuLSVzRBeDVdFfDlvNHhnbprMmRzZPBVLdDvZzdqQZiLlKzZkIzQqEbrBbZvslUxGgEDe' +
  'zZbAaGmBPrLlmMRFkDzZmMWZSVWEZyaaSsWbBTtjJwApPvDDWwdRIfYcDdUuWwnuXfUnNjcTLIZZzzil' +
  'CJYyUdxKDpwXrfcHSsDdNRybgXaACcCMDEEWggHqQLCVmlLMvGpPEebBtTnNPyYIiwYdDjknNnNuULIl' +
  'ZzDccKnVvSIiTjJWwVlYhTzXxZoggGgIEZtTgGIgPCnYnoLRXcPJPPlvvUuhYtjpPWMexXEejJERPayK' +
  'cahHAtTOINnczoOVOzVJsKMcCbBZCcJjJAMGGWyYmMwEmqQfXRpPDXgGxhAFDQqMQJjwManSCcCIsVIi' +
  'TthbiQauUZbBztfTtEmMEwWcCeUeFvBbtdlIhXRtcCpPHEQLmPxVVoepFfxXJOipPGuUdnCczFfJYyVV' +
  'WwIiaFPxVBHqcCQsSwQQqehHoHmMVUuvSLlksnnNqQNBBNnNTtqUuMmIGHVvPpSsoOQMAdDuSiIcrBls' +
  'kKLeEFBbmfFMfCqDUuzZTpPFSTIWrReqQjybBzZYNnzDBYtOfrRdDCcKVqaACRrcOaVZARjJeEoLWIpP' +
  'QoOCcvRryCsXOoxSVvmMICcsXvVJjcMmiEeIPpMbBBmMDhMHBSpPpPskXNAaJUuHRrtCcwbGHOFfdoEs' +
  'qRrtTQwwWsURrwdRHtKPpdvVvVDgTDmMxSIDuEeXmMRrpPeIEiwDBbVvHvmSBbJjbTaAsSNnJkMRrXxe' +
  'FnKydJjDgMaAMjJGgqQhbLYfEQUJjqHwKtTkyYKpPpmzlCcFzVvrRJjiZzLEelxHqjixIcECiImdUGqZ' +
  'LTtlCccCTaVvJWwdoYkfGnNplnbbBCLlKOlLwfFWZzMmlzEcFiISPaApaSZnjksBGOoLldzeEwfuGgXW' +
  'hHkPcCvumnCSIipWxXaDdQcuLWXKsvpPvRrVdriFfksqWwCgnNtWaCsiChVvcDdpkKUqqQtXxTkKopwV' +
  'OtGBJmMJiLobEeXnNxOojhjJrdarRAGtweEqQvPpVjJpzGJktTjCCoOcKnqQWhIiHlqtcCIngMmxXZId' +
  'afKJqtfGHgGjxXKkwVyhsAtpUsEbBhTthWwHNnHpXoOiNYyntTZVHRTqQBbbDdvFfLbBaYNkakKTWHyO' +
  'PgGCcpLlcCfTDRraAXEisgGZpPXhHhHiFfKGiIdwjLSiIUusloObBAFNCdiMmeIiWmwEeRJjRrNnbdMn' +
  'NnuQbajhHQqeEsShEaJjyYGCAtpWFBfbVuvndDzCGswPfFIrRifBhHMngGaAJdDbnSrXWwFfxijWMFsg' +
  'lLKVzSYKKnvmPpzwWJjZuiTtBbJjwQRroOrRqWPtltGeWwChLYSdKBrxJjGKkgXQppQfFqMwbBlZEBsS' +
  'sSvUjJYZQpPLqZzVueGtyvJjSIiyaCzGZgGYiIGgiZTJSClEesaMmHXxIiEeqQDBKqgGQNpTpWdgIiys' +
  'GJLxdbPeWOZxXJgWIZTiOoBzZoPEIynEeNJiIBYMQeHAKiROpOVSsvWwfFxNsaASUOUoQRCXgwWLtTtp' +
  'yYDdyuKCcgGkWbfCdGHhXxNnglWjrDrVvuQroKHjJOLPpPHhAgIiPpfYyYIPLlBfFbFfMZzilrtTRLXx' +
  'IBMmXJqcCQJjgIiGqWghHLjJbBlBbGmMwWDuUdsvVDcUTwWWNtXsYJnJWqDdVkKXxLlftwVhDdeEWjxK' +
  'RgtOjJdGgFbBBbNoZzgPkNttTQBmcSbBOWwouzQnxXbBNbmMCcCANmXmMFIvVxNDtTudNqBbQALPDdMf' +
  'FhHkKFfsqsfRecXbmdDVgGpOpRqQXxUuksowWOJoFfCQXqNpPaAaCjBAagGECRjQqJQqLCclYOoJBfha' +
  'okoNEeWfNugBbxXGgBbUvVuIrRiNFuvVBbQqUQnRfFrRxeEdecUuDdCKEBblrZHlXJkEGHMKmMkmbBUu' +
  'UuWwMcgeofdDFcsSNqnQORwWdDpQqWLlXGnNkZzKgNOoiPvfFiIzMlwRrWCkhiIqhHQRYTaWwAqQtxXY' +
  'yyvcWwVAOlLqQcyjJotTcuUqfFQgECqBlLbWlZYyULeuCXGiyYLIuMAsSaMeUEiYpSJjrxXRcCJJjjsP' +
  'SQqsVxVvXBbvECcUvVIMmopIibBhhHhPMRjiIhyPpYYysShbBDTsIFSfCAacxrtTKsBtTkKVGTDdxXtY' +
  'LdDGgpPmMRoCXmWSCwWAacxidfFVSnGVtfFfQqIgtrCYHGdOolgsPopTtPmSGiCcfIiVvCtbyYBRUAMY' +
  'PgGYDPWHhwclLKkQmMYyYtkKVvKSssQXYXmOOuUoFIGWOobBKkwUWpYyapoOiIuUVmdTtKrNPlKkOrHh' +
  'gGtAHRyYUImwWncgGBPpqnOVvypyOtlLQOUBbeNnmHhMVSsdkNnFfifFIJtoOXiWnITaRVOoMBztmoeE' +
  'COOoNnuDdcDyYJjlsSLBbPUVuSqKkCHGYGGkyYKiIUCcUuMmHyTeEeHhtuUTqHIvVxXkqIEeMsrRSmac' +
  'CiGXvVwxFxXRqdDcCzWgGsIbaGfFvwWVXxDbSdSnLMFfXxLlmDdjtJjTlWwfVUufFvJKaAkHhkGRrFGw' +
  'iCnABEFDsSntlvZzQqIicWxXYWEMTKkXmNicCyYIWwOjHhVfFvaSsKCdTesSUhIipzZNlDkSslHczwWh' +
  'tTRrHOpPAHEvVxtiSaAVkKHkTIssFLlwWGgDyfLlcCWZzCcwmEHAAxXEnCgGmMchLGTtgoVvCczZxXvO' +
  'boOpiYjWsOdDvqQVEUVWwJohVoGwWfOoFnNGAadWkKikKkKHtThCcnhuvVXkKRaADdgGLlLlrxzZPGgp' +
  'XIFfhkECtfHpfyegGQLZwWnEeCWyPyYpYDUBbcwIiWiLzbBztBBQpPquBYCfnBntTJpPgQRrVhbBHNYy' +
  'YUtTjdDkKgGZzbuVkQUkTZzIobZCcqTtQIRJylIXermMlLpjJJjwPpSzxRrXZnZAaZzDuihmVKkrRoOj' +
  'JIjOoJUuidZztTgvvPpAadTrROGNwQcTtmMOGSUurHRrzFNZzEqyYTsSRCTtsYqGYvDnyYjrRrxjXIiI' +
  'igInNiGzZUuXxrRjRrpPqQqkKsNQqnzZDTtdHhgmfOosJvDvFYmMCjJjLleymNHRuesAkGiqQFfmMIMm' +
  'KStaAdSJEeGpGLJjslLSpqfvSaAZzrREUShDdfFEHVzdcCDFfovkpxXPxXUuGxlNSuSYEiNnoOWVvDFB' +
  'tAaFsudXvZzFfuUOobBwxumpSloWwmfFMVLllDEeEeqqyYmxQuUjJXWhHZzVvilLQYQqyxXOoFfBbsSZ' +
  'EDUbBCyYcUZmGgkGwyqAWwaEQqeoOnBDPpVhHDdYyGGLlPwAlMtWtYsMJZqeEzLcCWEewlHhMUlLNdDn' +
  'VmaWoOhrRguUKlLmMqgVPfFpaWwAPkKvQYpPyQbDdpsglmMnNyIiQZOoOjJpAaPnNoBbaXQqsBZztTUu' +
  'bpNnVvYyHWmqJOoEBbzZGgjJjJIIioOiwNOiITWnCcRrNwtoxJjXLlhJjHNntTVwWUiFqxBNnUTtLlLx' +
  'XjVKglLSsYyhXxAaHpAaPgSsnJjjzZLXxlPgHrdDfxXFftTcCfzzFfZeEZfFFFFBbfyYuUHkuSsWYSUP' +
  'EeCeQqEcCczZjJtTuaOlRlLrLzZmMBDvVqYUuhChXxjJHFfWHeRNnrQtfGQaxXsUMXdqigiWZRrzBSsR' +
  'mMrFxINnNzZaAabBtTeKcCGizZWwpaGbBQyqMpPSsCfGpvVLrIQKidzrRNFzFfVvxXxRUaWiEZzFfQMF' +
  'dYyDSTIWKFfNvyPSdJjiIDyKWPCNLOVvbBEuUrRFpPfCFlLfcVvQADdjSxoEkoqQOKnNFLRftWwVaTtM' +
  'mAvTFfNJjRrBbgvVKCLbBIkwpcoqrYGgorkKyGgXnLgiYKHHhVvfhHGBhoguUBIibvZzWBbHhHhusvUc' +
  'CPpfFubBKkVSsAUQpPUuLWYFPpYsjcVyYMQweFfPnDdNOUQivQosYDcIiCvVddhdDHCcuPshVvIWwiHE' +
  'XMmMbgGeCcOoBYlLMmybPiMHFmMfgBoIVvWwiwWsdDxYzZKkzWwbiAHoGgGgbBMSsKXBQYzIiKBoCcOk' +
  'dmaknNKAtFftsSKkgHhGVQqFHJDBCcnZMmpYkKsZXOoazGgdBbXRrIePwMzQDdtTSsNLllLbAfeIKiIG' +
  'gHGiXYwWMmIichLDBoOwBbRFrcffFDdFuZzdnLXhjJaUxFCcpPmKeEMmkMiWwIzhHnrafFbCuUWwoEem' +
  'NnJaEeZedyQksPLuUlORVxvmiIvwWVRYZBgBbdOkvpiINLmuUvNnVMAtKkTQPpBbMmqMigKUTVEeyLEQ' +
  'quWwUDVvBYyRrEQGgbXAaRrbJjQDEKkRrWwenikuUSsHhZUqQMWxGZNipPInqQkCckrRrPccCRUurCpO' +
  'nVdbcQwyZpLlbTavVQfhHntWwTgGgpJvVphRrhIipJjNnPHEPUboOhQICoOaAfwWJFtTfjjHhXxlLLlL' +
  'lhHjROohjJHZOljJnKjjJcCJjbrNWicnNMmcJdDZFfGPsSzgmcCcYdDCUrphHKHhauhwmLKkcHhkbpPU' +
  'exIyTtohYsSyjQBbRraKDXUumRxXLnNKDdQCdIiDhHGgdDcMSsoOdfhdEgGIXxoSEHusGgFfCtgpHSsB' +
  'oqWzZTtLlwfIrRZVZPpKvXxmIiMxXVedSsrvVTNhZWHRyYaPYwWyyaAgUBbTiqoRSsLmMOoSsHdDztem' +
  'bBaAmMxROoOZYydVvQLHUiVJyaFfvNngGVVtVwaAeEzZWNyYaPpjJFPXGAzUumxuYVvVzZvyUXcNnChH' +
  'hraKgOoGkPrVkKvwWTQUgdDTyYZeEKkJjFogGnvuUZzrYyRPhDQLBbaftTiIFcKksSzWkKWZGXxgnNzn' +
  'qITsJBbLqQDTlfjJkKFlkvsBXtUubtTYyxXBkKTxkOxZzHjJhAaRCoGFfqQRCdaAAaXxdDXxCYyMmwWP' +
  'pxNLlAqQGuSpPsZNPsSyYeEAIiTJsJXJjPcyYfWAfzbBngiYNlYyVvEEebHJbALrFIiELjJIeIgTOKko' +
  'eWoOwpyYPWYEeylLcbkPpLHLkKlnNhsRrSaAlrRIpeWwEQqRjiqrwWETpPxUuhHXrRdeELlJjeidTtVv' +
  'VLWHhoIiOfzqmFLyYoeEoAaLaAcDhxXNqQZEezsSnHlMOTtMmgYnjJdWAUSgudDAwbBlkKrVZzrRymel' +
  'lCyvRddcCNrFfkWUOfFfFsxeEXxXzimMhlCctzeIiEgHtPOkKqKbuUKkBPLlLWgyUIiAaWlIfacCaAEJ' +
  'CIinbKuUkeEFSsGDoDMmdOUuBrVvRPpprxuUvJjbATtTPvKQqQAbGTQLbKHhkfFlOoRhPpUpbBeKOVvx' +
  'ikUDBWwWAfxhHXErcywKoNQtSsduxWOqQodFfUdKNntzvdYgWxRBbVdDvRVvoOWlLXWwJjHaYyAhyhHS' +
  'MnMmOovJzZLlLNnEInGgqQAaXxAJjgGstnrhAOtmEjJnRylLxzEPpeGoXuJpPVnNeRAazvVNCACcaBbj' +
  'fvSsSzmBWwioMugcCtVKyyEKkbkWgGDhCJmMgXdtTVoOQcdNjJnaBzZiwBnvFKnGVvfZRrwkopPAaHxm' +
  'DdboOBCoOTiLlCjYmaAhHMXxmqZAazBQsxnqQSOoaiPpaAIhUeEaAFfXRJpPwNoONDFfdfNEpfZYOoky' +
  'YjghtXYXxyopPOKDgEbeydDYZoOhHOozbaASHhwGEQqsWwbBGmCcAylLYkKhSFfsgGyZzUQOoFfquYyH' +
  'hVvqDdQSsSsgRgnNsXFjAJGUXcykKJjCtTclsLlquUtWPHhQGgqogJqQDLldNLlzpNYMmySVeEBBQrMQ' +
  'qVFFNRvmMGgsSVBsSQvVRDrRvmWwMIiOoYysVpPrzZcCNzYFGgrRTtfnxXaAPpuqQuhHqQuOovKbBoxX' +
  'OVvXxOoShGgHOoRNEGgeqQQBaRzMmZyWDNHhUForRatTiLlEPHKDdmXxXYyBceWoKkOkCcXSrRgHpAmM' +
  'QbKkXxyJjYBmBjJbfHhJjJSIVvVHhviFfeSxYfFOlLnadDAmxXMQqNvVHrVvYymnNMcCCcsStTpEePgU' +
  'qQPGtTgArLrRHNQjKMEeAgdDGxUuXppXbVHhPwWbHPpqQMAaiIDJHhSsjOYOoNhHnUrxfprRsaAaiIJe' +
  'EsSWwmJfFTaAtjXFupPWwYTEeShcCMUufFZnMUuzZoORrAaggEeyEetTLKOcmSGBxXXvkuUKVBbbZGaw' +
  'WqWwKlLkwOoQqGgwxohMNKxdfCMrDBbdUyLlnNEzZuvVJLlVFDJRlRrAbBxXCVQUsoERreOsSHhSXmpo' +
  'OjvMmFOoghHGWbmMUuyYHZufIKzZDvrHSeKkQPpiIBiqavKRMpxXxRdmUTiecMmCECcGLcCVvWDdwzZs' +
  'SENnjJeqMmVQMunGnwYyEoOhbfFKOowbqQlXxnNGizKKknQqNJaMpCcwjnsSlLNuLGneENRZSjJszkCO' +
  'uUnNDyGcxEPMFFfgDIZnNfFEeevMXspPSbBhuKkUCnBQGOoAaAyYgGnNqQagvXrEeAamVCEhHePGWFrz' +
  'ZRGgcCfwfFgqMgGlLgpPuUIDHhIiDaAdwHbzOHhoZHRrSwmdEAaUwWuZPihHqPNmblLEPGxmOoMwKVzZ' +
  'uBbdZzQWwCcGPFfpUNhHUunOoCcuxXBwWVvAatRrZRrzDgVzwmMNeEHbKrNnjJCTtMmcdfOqlLErREuU' +
  'vwjjyEGWwJWUhHbIiByDdgGPpiIPpFfIrRBmMbHtTuGeETXxJjdyNnVvlqQYDkyYTtYrRyyYFlETtjHu' +
  'VnNsyQbBnSCcsBbOomMjJpPAkFPzhCrPDMmFfxrPusSEeJjUQqCcOUWEMmXUoDQsSNZtmMqPBhKyYyNJ' +
  'jRrETRrteEemaAYMVvKkmVLawLchAxsSmqQkKorSVcCOovsFEefFtwWTyYMVvmLSKkUmAayYozpPZOMu' +
  'aAsccIiIiQzZqIqoOdDXxQOMeWFBIHGOoDpPdeEGfFLtJKkxifoOEehHZXaswiDdITtUEeuWqQExZUuz' +
  'FVveHmMhnNERtTrHraABAakEehOlLwbdFfcsQqSsaAsSSyKYxQkDGkKpPZlLkTMmtKuNrwemCCygGSsM' +
  'hHmgtZEeeELhHUudqRlLCUKkAhHJHhZOoWwcXOUUDduAhdAacDHYPnnXxgkTtBfTtDdFfHqrdDRnkmMD' +
  'deEwAAiUDdzOzNaAgGCTmMtWlLbgGEeuUyBVfFwjJuUpnKkOHyYXxHhlLtTwWBbFfjwJyYCGggeEnNGc' +
  'aOoJjyYLhHXYyxWwluUwfGwWuYJfsHhgGKaAuUWQqfdDfWMmmJwpBbJiIQlIiRKJjkrrGrRobbkRjCGg' +
  'cmeYvkKVzocMmCLljYQwWTUutCMMeEnpPMhfwmMlLWjWByOChPKoOkSrkKRtlQaAqGHQAaqQqJHhjyNn' +
  'YLKvxXExlLaAMglDdLZzkysxXSHsULwDKkmOrRoIidoxXutTrWEehDpeEwJEyYUUKkuyHHWhHWRrznJj' +
  'JTtcDiIgoBSsUVVSgUuGslhKkHOoErYyReLCrRaALBbbBlXUugCwaAvVfyIEeNJjaAfFcCnIiIifwWwZ' +
  'zLVvpPwpAYyaPaAABbGgxXlDddQuVvFfJmMiuYyUeEIjzZGnNnNghRDcwzYdgTPpImMqaAQofRrFyFcE' +
  'euMmFftTyexXlqgkKOoGfFBAacCjeLeEPpJjTtFNVvVasEeUuiMDdcXDdxpPBdIiDScpZDDkFfehFRrf' +
  'HFvVrCVDdvKkMrcCRmcoaATtdoOvDdtJjTUvLIilVtfnNPCqtsSTZFfFffFtTznNnSrQqCljJLaBbBdD' +
  'oJWkKwgRrGrLOinUuqANrnWOLTstLtbBThtTNMWNnOwKXDdxktTYqQXkSQcHAnNCcDfXxyYmIHcChWqA' +
  'ANtTUYnNfFyeRrPFfpRPpEerGgXwErwLvHiIuHhmMAaUGURpPjsoEemMerhHPpGVeCcLhbBuTlLuDAdq' +
  'lLQmMYypTtmxSsyYIiwvjJdDeEfjJyaCcAYDrcIiEeDaAdHdjgGvVjWdFfZtmGgDzZzGgZrRNYynJLlb' +
  'SfFFcCqvCXxcEeBGRtTBdDsAOonguhHUhJwPpxwWXfzKkGzGxGpPnODbGzcCqQKWxXQqjJckKCwtzQdD' +
  'tTZFXhqfFQGMldmXEHsSAcCWnNVFzZHhCcfwFfhHfFcRrCzTZzwWVvgGxYQLlrlLGBbgiNuzOJjoKkJc' +
  'CxCwIiWpPcQDdtxtTAjJabBOjJvbBVoDNIirxXRwWqQxXmiIgGMuTtoVvOwVxgYFfyLQFiIfvwWZzVUu' +
  'vLUuIVUEeGgFXxfYYyyEqGgjJQLtThHSsnNHhHhDdXxIimhHpDdcTTvVFRrXzZHHpfFzfEuGgZxFfXmq' +
  'qcSgGsAYkFnNqaAXfFqjsSHhqIiKkkKPyYpQvaAweoJeEQCgGZzclqQLMTNJjnbBHrNFpnejJxVuYFmW' +
  'wiIAhGyKTthHXxLlHFpPfhliqQIuYYXxyyPASeiGgBHumMKSOYAaIZziyDhHRpPrqQlLMIimgGRtTrfF' +
  'wsllLGKNnWWweMmEEeUJjuVvFfMmYytJjwWTAaPmMvqQVoDuUyeEYdAaOlLXgKkMGgmwtuUTpPmtoUuq' +
  'kbxYyBbXBGXeExPprVvTkiBOoZzDdRVvrRojkKuUfFcnNbBJeEjMmBbgFSkOoLlgLlGrRHBbhtFJjfMm' +
  'sCcMSNWvWfFuFGsGjZTtMmzAsJpEhRrUjeEqQiIpOtAaOSrRsoXOoQqVvbBeYUnNXLlzOoTtTFfYhCca' +
  'AWFdDvVvHHvVhEGgemaHTthWwOkLhHlfCcFNnbBgHhEeDYiJGtHfFTtEehzAuUzxXoOthAzdpPXxEFfm' +
  'TEezOoIijuUDoqdnNpdDDfOoUuVJjhBbHwHgmDdVAKbBxXyQOoqaAMfFJkKBbtTAaDdfFNiIpRyNnXxH' +
  'hYeVvERqSskKvVrRVUurRDvVfdAacKkzZKbhHaAmBhXxXhiSAtKkuUSsVvIWwbBhBNnEmBbPpNQdiIDK' +
  'fnnUlLYMkXgGoOxsSKmsMYyfnNFtTGgvVISstOodDOoPpcCoqQFfpdZzDgfkKTMNnZMmtcsiVBbweEbB' +
  'ZuUgmMzSsZGjiItTGgEeJrRoKwKrBacCMCrRcCcrKkRdDcSsSsCuQGJjRBEebcIihxXHPRQqaAhAaWAn' +
  'mNICmMVvclLWEVoOOnNsiISoPzZnCKkZiaADdsBbvVbYjjiIJLnuUNIiHhBPpQPpqbgGablLCbBtTSsc' +
  'mMfqQnBbwWoxPpyUuThHtYGkHBqPpdHhIHhoORlLruGgQyYqPpUCcAaRrTtRcYyewWtmJHeoOzZSpoVv' +
  'SswSMkKwyOoqaEeWwPppPJjirFfEAODOjQqqQdZsSzDOXxZwWjJzvJJjBbrRLlzlLZcCiprRhHrPhjKk' +
  'lBbEbBspPSzUuVOoYZfVvFPjXxJMHhIXxwWiUuBboOVACzqgGQXmTPpCqspWwVveEfFXxPBjHfTtWcCc' +
  'CLXhrLwASsTtwMmjJZdtTlUuALDdliIsSHDmMwfeEGNBbnFfXxhHKWKlLsDdDkKkaAZzijJIhHhhfLhR' +
  'rpNhHnPsjzUvVKQLlxPpXqsSrRzdYgGypPDEEeyzZYuURcCRRWfFwdDDdaAdDrraFfArOvVTxXLlNQqn' +
  'ymsfSsSMmJjsKkhzZLqQhHasKBIiSdiIEnUuNeJjYyFfDdLlPUBsfOoVvFSxXrSvVwXxbYRmkIgGJjiU' +
  'uGJFfWTKgGvVHhkvVCIitThHdKkoOKUIKuEeNYyqXXxYQeIiZqaALJcCBbjSVEevtBnJjIUZRNUIizDd' +
  'xopRfFBPpbjPfFoBJjbEWwSfTTtNntFsTSJjlkpHhrRyRrIjJievtiIHhBmymxXBfFBiHkivVgGHIiyJ' +
  'jYMqbsSnxjgHiyYfLnNjlrzZRhHdwxIikKXgoOhERkKreHVvVvRrkEFfeKcRhHvWmrRCCccRrPjJcCpz' +
  'ZzZKkAoFfvmMCcbKFaAeEfmMkOowWtsDdcJSKkZzLleaJLlxXjLpPpBvViSBXbzZKkyDASsyYfiIUtXG' +
  'GgpcEPMWwYweErRnNEuRTBHkgGmfFMLlGgHYaDdlQqzAvVjMhEGkKVvgaAuUPZzfCceEAamMMmvVFpGg' +
  'FqsSLlQdDvVBZzbQqIifeSsexyNnYZzvRSsrtTsruGgdkKxEFuOoUAhuUHinNteETYlZzwWKPpSsILmR' +
  'raAPZJmqteEhHRrWwrWgGUufFfUmwcHSsWwhJDdarREQqeatHiIKBUiZglbSsLlEeBanPhisHhShaAHI' +
  'XQqDEMXKkxXxLlmNAastTsSSNmvVnqbBvKkWwhJEekKxRwWoORWwPpaAloHLahpPHrBsSGgSCHqEtTIx' +
  'XieLCcZeEzIPOUXxuJjoFTngGiIQqrMmRMKraAmMRefFEEeLwJjtxERdDlLJFfvJMPDdpxapxXZzUyvV' +
  'GgSsAMuUecCEmacaMjRSsrMmQEeqJmAHOQkKqYyfkpDdPoOKFxxXmMNpPKXDMmZJjJFKkfCcOolLVoqQ' +
  'EeUwkGEeYhPpSsdGgkyYXVSWVvnNHhwseEzKaADlxXtTRrvIiCcMHhEevVkLlfEvKIcCoJjhCbgGIkyD' +
  'ufiRAarRrOoMmIGsjBbnLlkKoAaONJdDACcvQnDuUzEwFoOHFfVbrRBPPpAcbBzZoOujufNnFNnViIZz' +
  'IGgoRrgOAaoilOEehhCcMYyYhCcXxOoaAdMjWBbwLnnaEeFfvVdJjtEjJWqQIUdDiIpjUaWzZGgwNROo' +
  'mMUutxaXxBtTRxXIiZgpPJjxXqlLSsQjJnNGgnNcisxXaaATtTAaOolalLALtMPpESseSQJWwDtgSsLF' +
  'AKkDdqNdDFfxsRrYRrllXkBVvPpbxXrNnTtRBzKEnNixXmcxXPHiZTtpCjJDdaUQqGwJSEWwBSxXsbBt' +
  'iITsSzZbheuYsSHWNnNnDYEHOjqQdDPOQfFqKJjkEuSHhagalLAVuzQecCuZgbqQvVqEMmeudtTAHwWY' +
  'yibBIheOrRjGgJqQCcoJjPpEvimMDxzZNktlLUuTMmKWwHVvRYgGyreXJjxEFFfaANSinNmSspycXDGU' +
  'ugvVnNfvVFdJfFAaJXxVcZzaXYyyIiQlLqvbBtEnNguUrzFhFficPecCEeqQwWWwtbbBHFfRrRwBKkqo' +
  'WNoOnxlLDUuIaSSlXxPtomMOTpLonNOoOxltTLNnTbBakKApCcPBpnNdxRrOpSLljJedDEsdDPuaEebb' +
  'BJjqvVZzbBzTtAOBwWayYReehYEeaACcsyxXYGiZaakkxXKnNNJjbhHkKBdKLlkDTaAtgpPdeEbBRZzA' +
  'CwWcjJnNtTyzlJoONnRTOrRpLlqQnNWwxXFoEXxeEeZzwEOcCKkYjJWTtirRIwqbBlLxXsJjSoOuwQkK' +
  'OoqWUThHvNTosSYyVvOtnxXAGgTtgGReEctcCvAUuhHLqQsSeSsRrRkvVdEfFRHhaArfFpvtTVgGNBGg' +
  'VkKqHKkhHhtdYJGgtThnIyAXEexNiOohHIJjsTYytOaABpPQqTtKgDdfSBkrRmNnCdcLYcjJCVthINnS' +
  'snwWJjmVvIisSUjGgcTHdDhthHatgGTAbBlLTtsqfdDFefDdzMmpPZpkJhwtNdUbBuDbBvPpVnIDSQxs' +
  'GgVOmAaMDlKkLvqQvXxUSIiwWptTYyGgYyxcCNnHSsSMmkKTHhtshkDdYcOoOIvZEeKkOZYvyYVRCchJ' +
  'xLlWoOZEezHtTWvjxXYcdYyDCBbKkwWkKQjJqKqDZzIioKKkkhEUbBAamMZZelLNnIQqFfQNnpPkKwpP' +
  'MmchQGdWLsSaIiTsSuhHDFALqQwsSWaxJjLDCcNeEXxzZbEqYwWyYQiJUxpPuUWGgwXqyvVzKkrWwoeE' +
  'cCFfOTthQqHgGXxuUMZzPHqQvVzZzZOpPoysvBdDCcvVQqPjUuJtYNnTtBbTKmMKSsBKLJjwzZWaaAmB' +
  'TNKkngPOlLoBuyYUuUbqHDdoOiIfFNOoncChBXxbvuUGVvNLsUmeEMJVvjrGgkEeNnBbKxiyYrjJDNnd' +
  'xOSHZGgzQZpPpmGWOowgPtTzoOZojwWwWgCvqQVIicsxFfLAalXSlLtcCRjJXxuJiCuuohHOVvdXbnrR' +
  'ohHsJjJjAagGOiIvVYypGNpAisqQykKEZzCiOmwrRWxfFXPpMmqQDdOoGQUuqtwWTgjixXUuIfjJKkLl' +
  'PpgPpxXOOoKAkKagOoGMGJjOogWRrWwIiqLsVvSrRQBbSgGCcxXmrRjJUuiIgGRdRrDYydCAyYQqykgR' +
  'gGuklLZiIbVLlBbGgKkFmnNzZuoMOoPpmqQkwcTtCjJGXxxWgGJFfeEjlGneLlENVvSUKXGQzxnpPNvV' +
  'MmKnNkjJjWwDdJmVJwtTXqQIiHVWWeEweYyPQksSKUuCbBxXqKEekOwzsYjJyZzPKZzkpSJbBjvlLuUV' +
  'tTZOoqQlFfLmDdSstoOEeTxVvPXxzZpXKWKynCcFfmXxUsSaAUuWqqoOUxNVHHwWUxXCqQYyiSbBYdDy' +
  'YpgGfFfjJFPonNOvcChEeHhHsSfFggUaAukKgXxGEeCjJPMmsSsRkBbKSsfFwrYyZpuUPWdDwWwzeEhH' +
  'kKBxfFqTtesSEQNnouUOXbqcqQMmZhHsSgtTHhzZoCnqfFVDDsSiIdLiFfIdDBajJRrHhlwBbIiQjJDk' +
  'FffFKFHzgGSslPWEeoOBbSdDDMXxNnEhCcyYYBZABxQqZzvmMqjJXEpPesSEMnNFKawWIiUuSszKNVvP' +
  'pSfMmGgPpjuUgGdDBWwcNOExXeBRZlLfFjscmMIiNnJjjJITtfRryYGObBoHlNnWfFwLWOowFfMaALBb' +
  'EelYyudLltThHHcChhAiIvNiIbBgoCcyXIixFpydDYTjJZzYvBbvDdVkUuKTtSsdDSCHhcsoDFSsfOxc' +
  'CAAaaVvEeXdDKADVivlveXVDeEdyYwPeEpWvxnNEYZzyThHpPypTtPrWwRdDIiJPwoOWLzZhdDtTUuir' +
  'RzcCwWDoDvxyYYtTyNjjyUuCuUcUfFuYoRrabBANUucsSCrRImMqoLlOQiPJjlHpPOqQEoKiINjJnkMS' +
  'QqCbBVFHZEdDnBbGCcfFjxXeEtxXTJPvVpaiIhHAsEBXxXxMmbRreEOlLRroepjJIilOZZkKSsLcMqIs' +
  'wWStRlhHyYXxMXYykuUvVKoCtWZznIbhubBFfRKVsnNnYVvYyyGgJSsGgMmjxBbHhmMlLXEeFfoHhOqP' +
  'pQEeOSfYyVHEjKnNzNnbBkKyMmDoUdYyDdXUrRuGgEeIiJjjAkLsSYOPpPzUuNnGTSsDdbYygwWxXGUu' +
  'BOWCcwTudesSElLMmMAacyYNXxnJfFjnueEzgRpPrNhhuwdDWPXzZFfxyYJjkKpZztmMTNMmnnNFkOuU' +
  'wllaAJrFxYcXxpwWPtTjJMWwKawRryYWwIgwWCcGkKPSsOoGgmMvbBUqAaxXzUuKwWnNpBKsSOoERrev' +
  'lLpPtRUlLVNnZGlLgwvGgxUOMCcxXmiIsmMSoumdUnTThPPpNShVvyxpHhtTPjJquUQEJjtTwwWWYyot' +
  'TcoEelpoXCcwWxIXxNMhHmhHfFUiCcVvLVvlICeEiIKkiIWwlGzZNEenMdDiImDuwRrLqQjJrRTEeHVL' +
  'lvRKkrVoiIUoPnNpDyRrkKyGgYPIipYbBgGgrRWvTtPpVFFrRfksCtTcCGgGgnDdiXKnNkyYTKAEeSVX' +
  'oOZzmMnsShHNuUEeICcirRyYQTtqAydDaAPIiXxKTOADJRqpfFJVxpDdsShSsHnNPEmMTdeIVvcCdiIe' +
  'YyEdkKVsSAeEawWhHhHHhjnNAyaqBPCQqAaaVvVvzZOlTSOYyOiIMLxXoOnNTGvVcCJjQnRTtiIUuLQq' +
  'lgGrbBGgNnYySsjJVvrRNMmrNDdaUunaebncNnEeCYzZyXwWyvUKEjJqBbpPqQEWwqCApGXxljUuCJsS' +
  'XxjoOdDcQPpXQqxwjXxxXoODzZUuhCcHkKNnuGglKkdDTbBVUuvwxXwWWtQMEevZhHzTGgtpRrZOcCsg' +
  'GSotGoArRWwaOZzgPpNmMnaVXuUxrUufPuaMmZuUNEeOoXxCcBuZzUqQQevVrRbEeHhBjJtTqtPpuqgG' +
  'TtQHhUmMyZcMmCRriqQIloAQqAaQqaVvAeEZxpPXaOuUozATtHhaZAbBzZzaIPoUKZzkwXxcCKkXxdDz' +
  'ZzZAGNpPngefFLFXNnuUUupPSQvVHHnNhwyYWhEYTtNniEVveSsIdDylmMnNuUvVuUmMLdDijCcJIiIi' +
  'WwXxVFlEeLfmWwfVvFMxXYynNGWBbrrDhHQqKiIOPEepRLuUlrMTtcjHPWkKpfFmVveEdfOsSovVFBTj' +
  'SHhvutzZNDdnJeEXxSsEeeEyYYyKSHhbBrRaAUSrRsupjviIVJPTtNeEKhHtTsSkHUSsfFtTxXzZUoOP' +
  'HhxyYrJjJBbOoCZzcOYtSsZzTToLyDdiiIIMBTEeLltuTtRrLlBbVZzvhHOhHFyYlPJaAnjhHeEvVJlA' +
  'aLAoHfjNUuXAaxHhnmnNPpMEPaAcsZzfFHhfKkWMmcfFCNpcIRuUSlkrEEeAaWwetTEeqQaKkARKGgvV' +
  'AaDdDdaACcytvVHhTLpPBlLBbmMwZzRylLHzZhKkKkYhHDdljOoGGHhCUucZIiRytVvjJsuRrUhTgGFL' +
  'lJYqQUuKnWwTtpPLMQqmvVlLlQqNGPpgkdFXekKEGgeEnVYyvwZzqSsQvVvAaTRrrRCUuTrRtRTtAaoB' +
  'NnbaYyeEUGCcbFfBeiIsJGgcCAaXHcmQdDkIzRGgrbNAmaAMcCaRrthFsIiSJjgGGgfZkZzFuQqUOoOP' +
  'poMntTfFNzZzZssSMmEeqCSVvSsXxsCcZzOochzvUqoOGgJjQMXxyZTtzUuEeCcVvjJqOrUEeJjLhHlb' +
  'CcNeEFfKBbkZpixXKvyhHWGMCcBbVvmxXnzZQZSsDWwDddjJEelDfFsDdyYbBpPSlLUuwtTlLAVOoQqY' +
  'ybBvHhXxoOaPpuXvilLIVoOdDQqsSYyHvVmMsfiRzZPptTgGhHrPpRVgtCiTtWwlLIcCbBeEcgcCGLlx' +
  'XMGjJgHcYuUGgyFfWwYoKRjdZzFPpMmkcCakxXppPHhvLlAKkaYyDdAoWtwWTdDIiAzrRGgJjCSSbByY' +
  'stWwvVUDHhaoOAZzdukKaATEecCWwhkRrKBxOoByqKkQjkKJYZIpFtBQqYybDmMVvbBObBHhodUYUiIu' +
  'KkCDdpIqQWwnvVwbjgGlLvVcCJBBbgBJhHLljbWwLbBlvjJPplLMmMEekpPKlsAaKkSRrGKkcCvVXeEx' +
  'LdeEJjDQLlqpBbPlLpPbBkoOMsSDdmQqYyUriIRAHhauIiKMofjJoHwWFHhtTHhsSvVPpQqUufIiziYy' +
  'IZpPHhHhmMTdoOGgzZVvDOofFqbBnqwXxAaCtgjIivPpXxmHFfjJXCcUukqFxrdDOodDRJjnTAagGLBF' +
  'JRvEeVtGgulLUTpaAPufsjfmMsSSYFTPnfFTtwWiIcCQdDGezZeEExXLzZVjGgtiIfFHhndDvVAaNTby' +
  'NnVRrvvVLdDNSsNnceEwQqgQzjoOJZrPpyYJCCccZzjBbCcRJjqooxBEyYepAlTJSsolrRsStRrxXDwZ' +
  'ScCsvVKiIuUwWMtTmucCUSoMmOgGDAaTtLlTmFfgGdDxXHhkWwAgGZzmrwfiIlLPYyNnLzRFCcfrZuUS' +
  'sKkBbvVMiTJNnPpqEeQjpPAagGtIpPAUuqaAJjMpYgGXpPVvTtoOAadDvVserqQuaAyYIIiEerWwLlCc' +
  'PpxXRrFfRlLUugLxXWMiIeEOwDQfecCEeEKEgGNAaUcaACFeEQUuDFGPpgoKyYuvVUgGOdsSccCCDVRr' +
  'CcQzZiImMkiLlWAaAROOofFJjAkLTthnNZziIxsSTtiIyYSslLgGUUutZUuiIwWzzZRrLeyYbBElPpbm' +
  'MDiOoIILibZzuQqvVvmMVJVoNnOzZjeEGgsnNukKTtUXMmRXJjgGaAvVXxxLldAavVXbGgBiBMEfClLU' +
  'ucQqEcSbBPQqpsRrOHhNnoLdDeEILlktTYyDeEdKmMhNhHkrxXPnkKNQIiqpCCUCculbBMmLcuUiIbxw' +
  'WXbMmBdDlPyYpLoWPHbBbByYdDhEAaPtTUupzZhXxuFOoGEfFsRrWwMPyYphkKgBbDmKBcTtRzZgGEer' +
  'iIDkQqFDYydfTtpPRreuUpPEWwOoDdpxXhbBHPmOoFPENdDdDsSgGdeEDngWwTKXxktVvVEOoetTaSKk' +
  'aAsJkqQKJoVvuUgObOgSWMmWkKTtwkKVVvvKmCwoOQqWtqUrRzGgZOoxXXxuXxtTQqzZhHAYyELlqQwM' +
  'JjYyLvVOYyBJcCYyxXjFRrewWuUEowJnDdbBcCvVwGUuiIgdDGzlLHtThZyYonIiGgsrorubEjJeBhtG' +
  'geExCpPvaIdDiAafFgGOswVIiBMmbvBbkKWSSsbEeBTtYynNOoHRryYSshFfNYJeEmMJjjxZzaAWWwuU' +
  'uOqQosSnFfaAvVNQwagxvVXHoOtkJjxWzZwXKMmTpasoRKuUkzZwWAaAbpPGgEeBaNnnNHhzZjJgLlIi' +
  'OoMYyjJHZsSJiPCcxUuVNSsCXxMZzfzZSOuUodDHhsiIkKOjJTuUSszDYyaVzZvApFfFfPzcRsmMSOkK' +
  'RrhHhlLHhHnNPpEeVvXpPdDgIyJTtmMjEePxYyXoOlLINniAaLlZgnIjJJrRdDKkQuzZzbBMmZbsSBRa' +
  'BbhHDdFfkdDPWoZdDzxXXlxXBbaALwWaaAAbrYyOoFffVvMmWwYyrRXRryYfFBUOouEeMmbBbCmMcupP' +
  'UYUBburRyGrRhaAQqOorlFfLGgROolryYRAtTaoxXOCcAXxgQqXxzhHMmZvuUMmVgvVCcmsdBoObXxDS' +
  'yaFfcBbCAYNLldQQqqDwWoiaAICcQqOlLNPpcCnXnNoCcLlORrguUAatMUcCLldVBLtTntTFfIpPQqiN' +
  'gGpmTNFfKvVCcpAalLsSHhvTQqCLkKlOZzQqoIiaAVKkAaveElCcuUQqwWLcxXXRMmrxpBbnNlLPWwNW' +
  'QqwWwWwsSErYKkiOqQqQUuAaohHOrRgIigGGowWWwkGgKzZIaZzAVvBbmMrRBiIbBoObqQZzNsSnaAdD' +
  'RdDpPvWwwWWabaAZzEePpJjBAYyVveUAmMRlLrbxXBaIirRvVbMmBnLlbXqQXxxbBCcBWwkyYKDdnqQB' +
  'LPclXxJjyxdDbBZUPputxXTAXxazlLmMnJEwWWwWGuUXxzZCcHhrRmcCMfFAaamCcdJjozZODmdYyvVR' +
  'NnrmMZzXmMNghEpPerAaRgGyMmYJUpPSsIirRKKkkWBRrXiDdDdIqQRrxVeEvVvmMimeEMQqxLlZwWqQ' +
  'UuaAzIinobBiIDrROeEudDUVvnNeEhHvVexXEodgoxXaAOQqaArRpPGxXKlLkMmPpSsQeEqcCnmNAgHU' +
  'XdDnNxZzVsSBTtBBbIhYykTEyYvkPpKVeqjeQqBbmMmMYoOgbBSsohXxHFfOGycCsSSslLjYyiIddSgG' +
  'sIPCcpTSsUuqQYyOFfnNQUuqsSsATtaSBNnbQqgNsLSYhmMHhHylLcCgOoOoHPaAphEeGnpewLlGVvYC' +
  'cArXpPpPPpuUCVvFfiihfFHuGgTtwGgXFCcfxCcWUYyIXxZzmIiMGktTvmMVeEhDTjZzJtMmiIGaHhmv' +
  'VUWdDvAeEaVRlmMHheEtvVTKlLkSssCfpPmMFOoodDLyIVviYlkbBUuKRrOTbgGsShQqHHhoOhHCcxXB' +
  'YyIiffFzzZLwJnNjSbCOoasrRfFWmMhHNnbBNnwdZzDcCTtlLcrRCGgvDyYZzUUuudVCcCSsTtrXEQqe' +
  'cEeSsbBiInrRbBZDAWyYlVvLmsSbBMeEwyYPpWPphHwzZaMmBbcCsSISVvWRrwoOnNsCzZzODdotTZci' +
  'CcdDyPpxlLUulxXLXYtTGilLYyIqfFQgLDdlcCyYfXxtKkSsbBtyYjJOoeHhxXEpSSaTKkUeaAZBnNyY' +
  'bBzkBpPhOSsLPpzZjSsJloaAADgYgGyGdLTtlaqcEeVvcTwWtSdDhHRrsNvVWwnCiIGXxlLmhoOEeHML' +
  'lhHdDzJjztTZzdkKDQqhzwWZzwrRUWHBbxRrXoOfFNZzuUbBnhdDhqQPpKkuUFzZyYzhHZoNwnNWeDGz' +
  'ZqQZzgZZzEedCnNFZbGgBriIRryIiPpUuYmMRrlLsRAaCcrLlSgyHholLbBfFDdtyYAJrRjavVqQIizm' +
  'VyYvMTthFfHZAoOImMJjiTtlYyLpPjyfFGHpPIimPpMUaAsSubBKkTthkuUcCFfnNOoHIUuihKnhVBbT' +
  'tfaAFoYyQUuibyedVXxvDCcAaLmwIDmMdVviWMjJsBbSfrRBbcCwWqQOoFoSsSsCcOOodDfqQFHSsUur' +
  'RLlooOOSsFsSfhGGgGggyYwHJjlLhiIWCZzMMSKwWIJjiybBhdcPpCRLlEeIiTtFsShHhHwiIbXpeEKk' +
  'FfwFgqNAarRnAaBbQGhHfNnWzZCcIVvCKkcoOtTiUQqaAGGenNkKilLIEUtToQUupUusSPJjkGbeAUua' +
  'EBBwEeyNrUtTrFLaAlOoUuhHTwWtDSsdftTRsNnSiIioODtTddYyTPpFzZfQqwWtzJSsqQEeQqFfjSsY' +
  'ybBsSIiQqZKkaAdAaHhxVvJjfKkFEKkecxXCIWuUvVMmuUsfGpPIGguUcMwWwWgGrRmQsyYSLoOuUDdl' +
  'qCffFFcCylLYEqQmMbBvVpPvXpMiIlLsmeEdDpPlZCcwWUuzLdESsYGBbjJeufFUEAEeaupPxXSCcjdD' +
  'fFPlCRrCcgtTCcPphHBrRBbbGaAlLiIJjcdDQqlLicChaAHFfILGgUKtTkeMXxDdmzZMhHsSFfmpuUdD' +
  'PQqLMsSmlZXOoDdWwuUxjaRHhQqrlpPyYYyIiRrXxFGgfeRracCAEEeLlOsSoLlSlLszrRZbBLxXAufP' +
  'pFMmUJUBeEiWTtEPppyLmdlLDKkckpHhPKvVYEeFfwWcdGgLjJXxZzmIipRrFftFfIiTlfvVsSFLPmRX' +
  'iIxMIiXLlebOoBtiWVvXxtvVeEsSKhHkwWwWCclQLloOqYyBbAbMTtmsSBqQGbHhZJoLlOjWktSsTqiI' +
  'QKwhHzguTtUNjIiJJjnGBCcbAaBiItUuTxHhMIsSEeDLbdJjEeDfFPiqQmMeEpejrRJEYyuVsSvqQUSs' +
  'nNnMJjUumNCXxcewWddDjJdMzgGZUZaAOJjoZqQzzuaAmDiIYJjyGqQdDVvgkSsyYNnBbzZKRrIJjiLl' +
  'VAaoIiOyhFcCjJgGUgGufHKIRrsqQSJgGjGgFfizZRrcCqKfFmMkbBSsXkKHhtUulqQLTogpTtOPRrlH' +
  'hLposSQfuMmcCaADdfFElLeiITtivVgPfTtvQQqgaAGqTtMmIinNFfaAoOVIhHiEtTepPAapPKkOowWa' +
  'AcCGgWwpDdPFHhoOoOKkpoNnOPnoOpOoGgCCccPsGgkKSNugGVvUSsUwWBJAapPjfFRrbYySsuhHrRbB' +
  'MmiTtUuNnIeEKkDrRQfLSqWwQVALlaEeYyQqLVviIlbJjaAzZtOomKknhHNjbBJgGYyYkKAbthHtToKk' +
  'OThHMmLlhHhMmbBfgGcCFfgGjJApPxCZLlzUucQqlySsYPpsSNOovVzyrRkIiAacTtXxCoeWSswJVvhP' +
  'pHsXxSWwoqQOZzJjMmpTtPiIGggZzGOojUutTcrRCEpPssSSfgiIGUuDKDvYymMYgGySsSsGgVEUuHhE' +
  'euUWwdDyYsPpUuNFfncxXLljJnNnNLEelmBbJjklLseEEmMSCcMmrRBbqgOQqoGEKkemMQTyOobBYDkK' +
  'jJdNjJxXnoZzOtbBWwTxXohHtPZSsHhAIiahPqfuUFpPJlLfFZcCDdzXxyYRFcGgCqQfQqDdQAaqtTLl' +
  'xBbXHhrcCTtsfFSsrRbBzgGwWzOogGQqXxkKNnhHCsScNUsSuGgcCncFHEXxehtTgGkKtTZJgvVWwWwE' +
  'elCcHhJjOoSqrkKrRVviIRnwWNBtTmMIiDwWjxXJkKKkTeEtTbBCsSsSIictWwvVaArhBbHMfKkFIeMm' +
  'EimQzZOxvVgZzSsGUgEelLcCaAGcCuiQqtlLQqsyYSvbvVBVnMmNrRdGgDTpPWwtHhuxXUTGiISsphHP' +
  'gpgCcGZzckKCHBbhnkssSSmMoYyJtTtNaAnTotpaAPFfMLlcCgGvVwdDIilLNnAaCcVlGwWgtRfNnkKR' +
  'rQnCcNaAPpqFxXrJAabBTyYYyUAaHhutIKkzZivVywIitTDdWGgYYybOoNnuUIiBKwWkEeWWwTtwuiIt' +
  'FfmdDAGoOglPpLaMIaQqAipBbZmMXxRUurLlzfFKgGksSWwpqQPsofFMmojoOJOrXxPpbBzPaTmMtApZ' +
  'TtQquWwUnNByQqYcCFfIirRQqYybTLlwHZziaaAAIuURoNnOnfTtFaAPpNfFAaHcCqQbfFqQJjBDRYyl' +
  'HLGglzZOvrRVonHLlMmhNnHCkKMDdzZmchFMeEsSKFfoOnNEXFXxsSWaAmoOXeNnWvVwFfECcXxTtSsE' +
  'dPqmLldLdDlDMQpQkKGgRrIiqBPpbhTtHVvdBbDxXlLDyYKYykeEfFYyqQBmQqZzvRzZzZrfFXPxXhoO' +
  'HLnyYtTWgaATZztMmRTYytrCIMlLmicGYyrtAaTRjHhyYJNTtvWwDdVnGgRrwhHRruUMUuIiYKkmMImM' +
  'qQSxXrRkKweEWzCMmcdDRRrisSIrrRfbuUGgLleENnVPrRDdsXxsPpAaSOoiIjaAJtccISuUstfFTRrS' +
  'soMuUhoOHmZzsSHhObBSsdPpcJQqGGggjpPCXHhVvBaAbJjaApXxTtPsSoOOovVhHETIiPpeueEawHhW' +
  'ufFqEeQUIiGgESseKkYAacCgGBbrJRHbBhcCKiAaIkOCcWwdDodDPpzZcCBRrMmFIBbvVsNnEejCczZJ' +
  'kKpPzZDlLSKXxnOosSNHhdDXxBbKRrkRryYHhDFpPsSCcgGfIyYidaAmXxqQFxXEWwswePpKkERwWrxX' +
  'GgCcFfCPaApcWSgGeiFfXxxXHPPppXxhXOUuebBOoroOJkKmMjRhHcqQdDIifdvVUuEeEeDtTTgGvVtY' +
  'nWwTxXNnOohHtricCQqnNXxeJHhjeEOovVjVvJsSScCcCaAIiseSwWsMmTcDTtdCtALhHMmmMDdhHWwb' +
  'BQqiIvVlavqQuUFLlfkWwKqQRrRrsSvhdDHVyjJPeEpmMeEQTtxXbBqIiYfQUuTtqPpTtcCcYyCUusSm' +
  'oOOovgGyYVUuMnNJKkpPjPpSsEeFfAbBpPpPaIgGQMnNKKkMmkmjJqFfWwifNnNnxBbXSlLsCaPAGgzH' +
  'hZGyYgaZzIylLKkbBYiEecCEEKkeeRrkHhzZuUvVgGOoBbRzZrgGvUubBFfVSDdRreEcCoMmUuvUJjuk' +
  'suClLcGLlknKkNapPANKBbkrpPBbjJDdHhxXmMwWQhQqmMJMDdmjHGgeEfqQFPpgEuUQqciKkICNnwWM' +
  'mfJVvmMwWZQqETteJXHhhHZYHLfFlfRrBbwWnNaDggVveEGGYydCcfFQLlVIieEvqPpAYWmMSswjJljJ' +
  'YpPOKkLlorRxXqjkKJQqpPQPpydDrRbvVJOokfuUFOoKjvVrRsSmMpPjJzSzZJjfFsTiItEezWwZiZzD' +
  'dIDzZYUuyvOoVlLbMOuUoFOoftTAAaUiiCcNnIjJoOnkoIikKOKfaAFagOoDdGpjAaCcfKaAlDdLkcCF' +
  'JTtdbLleEBPgGtTTcCtdDEeBbMyYeEmVYyhHvNnPpgMGgJIilLjOHexXEGUugBbJwgdDGWuWwWwUZzKL' +
  'lVvqQDSKAyAtTeSsEhgGHvVkdXxDLlGgeEKZzavVxCNnBbJjOocjJaAGgTZKkuUzyfFYEHOUuoJjhwaA' +
  'WXHqQhBbKyYwWkBbxQqTkKKktCtTcrqQgGvRrsSMtTmkKVNTtnttOoTxXhkKHCcTlAaLRsOnNoiISojJ' +
  'SsLlZrRaAuUDdSjTtJeEhHxmMWYywuMmhnSshHNXxKkHtTgGUXsCcehHESSsnkKRrNnkgGaAKkKNKkOB' +
  'AabcCKkDdJYyqgGgdDmMkuUeERrAawWlqrRIizvVZQNhaLlAiiIIHPpkKtTVvHhsrRSLGzUucCRrPpsS' +
  'zhHtDdjVWMmNnfFMmsJjLTBAamMqQbrROLltoOCcsSPpxXTYyQqonzZMmNyYtcleEaDKkdwbBWSsxXxK' +
  'kYEeyLHhlAafWwFwQLlqxXGgkKEbBtTeNnyFvNnVwWQCoOBnpPNbhSSsxXJjsMmHLLeEllsiImkwWcCK' +
  'MDktTKOXxhFWzZwCcdolLTtONnTqQtImYyoaRrlLAjoEeUuecCEezZEfFPpOOuUoFfLlGkKdeEbBzZsS' +
  'DUugBbJjJWqQwnNCqQyYgGNnwYyeEAXxaVaJjvulLUVUmMMmKkiIfFSsqRrcJjDdvVjJtTONQEehHqWw' +
  'nAamdDXxMZzoryYRlLwlLWBbcOHhnNoqaAQSOZbBzSsiIoMXrRxmUFfmaAMdkKDvEeNnQqdDVuUiIBbf' +
  'FghHbMeEmpMmPtmwWMOoTYyHhBezZoOykKHhikKIJtTMmjiiVAavbxXBVXxvfFKVOoSsHiICVvcdDHhl' +
  'rGgRLKkRKkYyrhZZzWtTSswbWkNnFFfqQfKNnGkcIiCKlLgrFsGeEUugEeSfHOoXGgjKkIiHZzZzRrtT' +
  'xJjXaAZRrzjJSelLddDDutgVvvEeVGbBbBbkGgSsKBeEqQeETAaaAWwiIzTsTtSsqQIifvVFStZQqQqH' +
  'GghxRmMrXrRlLoeEFfUbWwBOKkKkYyrVuUvVVkKiIZnNzvviFfqoOQInNVTTtOvVotTBbFftmMqQvRpP' +
  'CcTmWKdrRDUuguUsHhSGOokYyjJfFwcBBbCcbgGeEKJqQjKkkoOfFrRCcSsVvYgGuUPpeETtgGeEykgG' +
  'GgQqKkJBbjZzVKkIpSsPyYiDOoTtEEeYyJZDdfFWYyMmwhBbZzHXYyoOuUxzzSsZVvjJkiIZLFakKAIu' +
  'UPpiDdfSsxIiRraAmkKEeuUOoMXltTKLlkiIXxrRrxXRtNOmMoHhVbBvBKkbuXjJxyaAYGEegVvGXxhH' +
  'yYqQgUXaAKwWkBAaRJjrsSIiYiIyHhDdIaAkKifFZzbCcsCkKcFfSeXqJjQxOfFBbohHwBbWGXxEjOor' +
  'RJegZzbBqbBQyYnvVROorNaAhHJjEnNvPpnNreERboOBVTtQqqQYrRQqyNnZzRrqQxXxZgGDdzZzqQul' +
  'vVbHsShSuUuUEeXxsffFOoFiICcPAapRrBbpPIFdYyDAvQqmMVkKUeEuaXxPpHhliXxdDIAaLBbSsFvV' +
  'reEmMRrpPRuEetTzZXxHhHlLYyJvVjmMkoOSsZzKMJuUjkuUOugGDdUMmjYyIfJjFrRiFfKkJcCCcSzZ' +
  'swWGzbBZYowzZWVvkKJjwWYytRrTOylLFfoOhHfWSzZswGgKkPPmJgGjAayYMpJjpDduSsURrcmxXeEM' +
  'CLxXXrRtTooOIieETTttpPhHQqOxkKLlGaARfNnWDdmDdYyMQqfFwjfFbjJBJFrXxyYyYTtxPBbprRrR' +
  'XcCgFfyYcHhCylkKoOJjeEyeEYLuCcUYWwFWwIiMTtmOUuwVvWKkoOotfFzZSsAajJagGATRrAIiJjHu' +
  'sSUIihahjDdNnXxCcyrRiIRryYZzjQquULljJJYNnaEeAtaAMmTCckKobBOikKgGIkKyUGgljVYyLlvw' +
  'WleELkKJZzGgLMmbUueHhEfGgFBrtOokjEeJRwWKkrPpeEyUuUuzmMCcZxmMUyYugGvVMOomfFthPpHT' +
  'XyLloOYyDdYjKSsiIHFfgGwWhyYxXkqDLldQQqJbUBUubCcAaOodrRqQeEHBbhDdDwEePpWAadOoDCoO' +
  'HyYwWHBbhcCpPjJQMmqILlLlqQiGgCcMrpPJjOobBRTtXLlHmMhxmlWwVvTtLdDzSyYsZpGgQSYysqNn' +
  'PGPpnNlrRvVLgDDdHhwKkWHFfRrwWmMUrRhVDdnNqQvxXHjGgqQZzWwdDMmMmDdnaAMEcCemRrNZzouz' +
  'ZUmMTuUpPtTBbtOiIgxXGOpgsSiIYycCGPowWyYKjJkKJRrNniIjdDZzkQqJEeHhucCcmQqMCqyYlbBE' +
  'eUusSTxXMOomtNHhLVvLVvllnMmvtTwWKkVVADdDdyYaGgeERMmrnNTgGtnNvLvVwWJUjJuOgGojJZzL' +
  'ljwyYWiiIIzbBOouyYkKiIraARUpPZMmqyYQlLYyUrJXxjReEoOFfuUmMYyDdiIgXxTtzjJyaAxPpXYZ' +
  'dDyBbEeYMmzZJjEhHenoOxXNpPpTVvtDvVdPvoOVqQQqkLlKulLUrRcXxCrRnjJjJEeNinPpMmNIIbBx' +
  'XcCiRrWlLbBpPESsKkglLtTGewgmMgUueEZzRrQqGoOqQJUWwufoOBaAbFXxjaAGBEehHeEtTjJGBYyb' +
  'gKkLlPZzRWwrZLlrRzuUgGpUlLSsJjKVvkuBbWwFTXIEeixthrRpPHOFfEekcCKoZEemMnNowXxWUusS' +
  'xXOXJWwrfFRrRjPdkKDbBSspxhHpPQqHhfFNZzkfFKTGgiItjJnAazPpuXxUGWwgfdDHtBbpPTTthUNn' +
  'IeESsiuUuiIKkqcEeJjCgGeEQqbBQRrNDdDdaAfwWFnoOEeoOHhRrVfFIGgigGiwZzGgWADWwdacCOoS' +
  'sDdIlTtLWCcNnaGgAUurRwzZymMOovVjJZzYWwWwnWwreERxXZzLEelrRGgrRSsMLlSsdXxDmZXhEevV' +
  'WwYyeFfKEekjJEHUuorROxWwbheEHjJBFfIQqXxiZFWPpwfzzrZzRMmIiUmMeESsuozZQVvqOQTeEtqS'
//#endregion

//#region test definitions
function assertAlchemy(compound, expectedResult) {
  // console.log(`'${originalCompound}' to '${resultCompound}'`)
  Assert.deepStrictEqual(alchemy(compound), expectedResult, `${compound} to ${expectedResult}`)
}

function assertAnalysis(compound, expectedResult) {
  Assert.deepStrictEqual(analyzeSample(compound), expectedResult)
}

function assertUniqueElements(compound, expectedResult) {
  Assert.deepStrictEqual(getUniqueElements(compound), expectedResult, `'${compound}' to '${expectedResult}'`)
}

function assertRemoveElement(compound, element, expectedResult) {
  Assert.deepStrictEqual(removeElementFromCompound(compound, element), expectedResult)
}

function assertRefinedAnalysis(compound, expectedResult) {
  Assert.deepStrictEqual(refineAndAnalyze(compound), expectedResult)
}
//#endregion

//#region completed tests
assertAlchemy(null, '')
assertAlchemy('', '')
assertAlchemy('ab', 'ab')
assertAlchemy('aA', '')
assertAlchemy('AA', 'AA')
assertAlchemy('abBA', '')
assertAlchemy('abAB', 'abAB')
assertAlchemy('dabAcCaCBAcCcaDA', 'dabCBAcaDA')

assertUniqueElements(null, '')
assertUniqueElements('', '')
assertUniqueElements('ab', ['a','b'])
assertUniqueElements('aA', ['a'])
assertUniqueElements('AA', ['A'])
assertUniqueElements('abBA', ['a','b'])
assertUniqueElements('abAB', ['a','b'])
assertUniqueElements('dabAcCaCBAcCcaDA', ['a','b','c','d'])

assertRemoveElement(null, null, '')
assertRemoveElement('', '', '')
assertRemoveElement('ab', 'a', 'b')
assertRemoveElement('aA', 'a', '')
assertRemoveElement('abBA', 'a', 'bB')
assertRemoveElement('abAB', 'a', 'bB')
assertRemoveElement('dabAcCaCBAcCcaDA', 'a', 'dbcCCBcCcD')
assertRemoveElement('dabAcCaCBAcCcaDA', 'b', 'daAcCaCAcCcaDA')
assertRemoveElement('dabAcCaCBAcCcaDA', 'c', 'dabAaBAaDA')
assertRemoveElement('dabAcCaCBAcCcaDA', 'd', 'abAcCaCBAcCcaA')

assertAnalysis(null, 0)
assertAnalysis('', 0)
assertAnalysis('ab', 2)
assertAnalysis('aA', 0)
assertAnalysis('AA', 2)
assertAnalysis('abBA', 0)
assertAnalysis('abAB', 4)
assertAnalysis('dabAcCaCBAcCcaDA', 10)

assertRefinedAnalysis('dabAcCaCBAcCcaDA', { 'a': 6, 'b': 8, 'c': 4, 'd': 6 })
//#endregion completed tests

function alchemy(compound) {
  if (!compound) return ''
  let compoundArray = compound.split('')

  do {
    var changeCount = 0
    for (let i = 0; i < compoundArray.length - 1; i++)
      if (isCompatibleUnit(compoundArray[i], compoundArray[i + 1])) {
        compoundArray.splice(i, 2)
        changeCount++
      }
  }
  while (changeCount > 0)

  compound = compoundArray.join('')
  return compound
}

function analyzeSample(compound) {
  return alchemy(compound).length
}

function isCompatibleUnit(unitA, unitB) {
  return isSameUnit(unitA, unitB) && isDifferentPolarity(unitA, unitB)
}

function isDifferentPolarity(unitA, unitB) {
  return unitA !== unitB
}

function isSameUnit(unitA, unitB) {
  return unitA.toLowerCase() === unitB.toLowerCase()
}

function getUniqueElements(compound) {
  if (!compound) return ''
  let compoundArray = compound.split('')
  sortAlphaArray(compoundArray)
  for (var i = compoundArray.length - 1; i > 0; i--)
    if (isSameUnit(compoundArray[i], compoundArray[i - 1]))
      compoundArray.splice(i, 1)
  return compoundArray
}

function sortAlphaArray(arr) {
  arr.sort((a, b) => {
    let loweredA = a.toLowerCase()
    let loweredB = b.toLowerCase()
    if (loweredA < loweredB)
      return -1
    if (loweredA > loweredB)
      return 1
    return 0
  })
}

function removeElementFromCompound(compound, element) {
  if (!compound || !element) return ''
  return compound.replace(RegExp(element, 'gi'), '')
}

function refineAndAnalyze(compound) {
  const uniqueElements = getUniqueElements(compound)
  let analysis = {}
  uniqueElements.forEach(e => {
    analysis[e] = analyzeSample(removeElementFromCompound(compound, e))
  })
  return analysis
}


// output for part 1
console.log(analyzeSample(input))

// output for part 2
console.log(refineAndAnalyze(input))